// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package checksum

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"shared"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__
var GoUnusedProtection__ int

// Attributes:
//   - CancelRequested
//   - State
//   - CloseStatus
//   - LastWriteVersion
//   - LastWriteEventID
//   - LastFirstEventID
//   - NextEventID
//   - LastProcessedEventID
//   - SignalCount
//   - DecisionAttempt
//   - DecisionVersion
//   - DecisionScheduledID
//   - DecisionStartedID
//   - PendingTimerStartedIDs
//   - PendingActivityScheduledIDs
//   - PendingSignalInitiatedIDs
//   - PendingReqCancelInitiatedIDs
//   - PendingChildInitiatedIDs
//   - StickyTaskListName
//   - VersionHistories
type MutableStateChecksumPayload struct {
	// unused fields # 1 to 9
	CancelRequested *bool `thrift:"cancelRequested,10" json:"cancelRequested,omitempty"`
	// unused fields # 11 to 14
	State       *int16 `thrift:"state,15" json:"state,omitempty"`
	CloseStatus *int16 `thrift:"closeStatus,16" json:"closeStatus,omitempty"`
	// unused fields # 17 to 20
	LastWriteVersion     *int64 `thrift:"lastWriteVersion,21" json:"lastWriteVersion,omitempty"`
	LastWriteEventID     *int64 `thrift:"lastWriteEventID,22" json:"lastWriteEventID,omitempty"`
	LastFirstEventID     *int64 `thrift:"lastFirstEventID,23" json:"lastFirstEventID,omitempty"`
	NextEventID          *int64 `thrift:"nextEventID,24" json:"nextEventID,omitempty"`
	LastProcessedEventID *int64 `thrift:"lastProcessedEventID,25" json:"lastProcessedEventID,omitempty"`
	SignalCount          *int64 `thrift:"signalCount,26" json:"signalCount,omitempty"`
	// unused fields # 27 to 34
	DecisionAttempt     *int32 `thrift:"decisionAttempt,35" json:"decisionAttempt,omitempty"`
	DecisionVersion     *int64 `thrift:"decisionVersion,36" json:"decisionVersion,omitempty"`
	DecisionScheduledID *int64 `thrift:"decisionScheduledID,37" json:"decisionScheduledID,omitempty"`
	DecisionStartedID   *int64 `thrift:"decisionStartedID,38" json:"decisionStartedID,omitempty"`
	// unused fields # 39 to 44
	PendingTimerStartedIDs       []int64 `thrift:"pendingTimerStartedIDs,45" json:"pendingTimerStartedIDs,omitempty"`
	PendingActivityScheduledIDs  []int64 `thrift:"pendingActivityScheduledIDs,46" json:"pendingActivityScheduledIDs,omitempty"`
	PendingSignalInitiatedIDs    []int64 `thrift:"pendingSignalInitiatedIDs,47" json:"pendingSignalInitiatedIDs,omitempty"`
	PendingReqCancelInitiatedIDs []int64 `thrift:"pendingReqCancelInitiatedIDs,48" json:"pendingReqCancelInitiatedIDs,omitempty"`
	PendingChildInitiatedIDs     []int64 `thrift:"pendingChildInitiatedIDs,49" json:"pendingChildInitiatedIDs,omitempty"`
	// unused fields # 50 to 54
	StickyTaskListName *string                  `thrift:"stickyTaskListName,55" json:"stickyTaskListName,omitempty"`
	VersionHistories   *shared.VersionHistories `thrift:"VersionHistories,56" json:"VersionHistories,omitempty"`
}

func NewMutableStateChecksumPayload() *MutableStateChecksumPayload {
	return &MutableStateChecksumPayload{}
}

var MutableStateChecksumPayload_CancelRequested_DEFAULT bool

func (p *MutableStateChecksumPayload) GetCancelRequested() bool {
	if !p.IsSetCancelRequested() {
		return MutableStateChecksumPayload_CancelRequested_DEFAULT
	}
	return *p.CancelRequested
}

var MutableStateChecksumPayload_State_DEFAULT int16

func (p *MutableStateChecksumPayload) GetState() int16 {
	if !p.IsSetState() {
		return MutableStateChecksumPayload_State_DEFAULT
	}
	return *p.State
}

var MutableStateChecksumPayload_CloseStatus_DEFAULT int16

func (p *MutableStateChecksumPayload) GetCloseStatus() int16 {
	if !p.IsSetCloseStatus() {
		return MutableStateChecksumPayload_CloseStatus_DEFAULT
	}
	return *p.CloseStatus
}

var MutableStateChecksumPayload_LastWriteVersion_DEFAULT int64

func (p *MutableStateChecksumPayload) GetLastWriteVersion() int64 {
	if !p.IsSetLastWriteVersion() {
		return MutableStateChecksumPayload_LastWriteVersion_DEFAULT
	}
	return *p.LastWriteVersion
}

var MutableStateChecksumPayload_LastWriteEventID_DEFAULT int64

func (p *MutableStateChecksumPayload) GetLastWriteEventID() int64 {
	if !p.IsSetLastWriteEventID() {
		return MutableStateChecksumPayload_LastWriteEventID_DEFAULT
	}
	return *p.LastWriteEventID
}

var MutableStateChecksumPayload_LastFirstEventID_DEFAULT int64

func (p *MutableStateChecksumPayload) GetLastFirstEventID() int64 {
	if !p.IsSetLastFirstEventID() {
		return MutableStateChecksumPayload_LastFirstEventID_DEFAULT
	}
	return *p.LastFirstEventID
}

var MutableStateChecksumPayload_NextEventID_DEFAULT int64

func (p *MutableStateChecksumPayload) GetNextEventID() int64 {
	if !p.IsSetNextEventID() {
		return MutableStateChecksumPayload_NextEventID_DEFAULT
	}
	return *p.NextEventID
}

var MutableStateChecksumPayload_LastProcessedEventID_DEFAULT int64

func (p *MutableStateChecksumPayload) GetLastProcessedEventID() int64 {
	if !p.IsSetLastProcessedEventID() {
		return MutableStateChecksumPayload_LastProcessedEventID_DEFAULT
	}
	return *p.LastProcessedEventID
}

var MutableStateChecksumPayload_SignalCount_DEFAULT int64

func (p *MutableStateChecksumPayload) GetSignalCount() int64 {
	if !p.IsSetSignalCount() {
		return MutableStateChecksumPayload_SignalCount_DEFAULT
	}
	return *p.SignalCount
}

var MutableStateChecksumPayload_DecisionAttempt_DEFAULT int32

func (p *MutableStateChecksumPayload) GetDecisionAttempt() int32 {
	if !p.IsSetDecisionAttempt() {
		return MutableStateChecksumPayload_DecisionAttempt_DEFAULT
	}
	return *p.DecisionAttempt
}

var MutableStateChecksumPayload_DecisionVersion_DEFAULT int64

func (p *MutableStateChecksumPayload) GetDecisionVersion() int64 {
	if !p.IsSetDecisionVersion() {
		return MutableStateChecksumPayload_DecisionVersion_DEFAULT
	}
	return *p.DecisionVersion
}

var MutableStateChecksumPayload_DecisionScheduledID_DEFAULT int64

func (p *MutableStateChecksumPayload) GetDecisionScheduledID() int64 {
	if !p.IsSetDecisionScheduledID() {
		return MutableStateChecksumPayload_DecisionScheduledID_DEFAULT
	}
	return *p.DecisionScheduledID
}

var MutableStateChecksumPayload_DecisionStartedID_DEFAULT int64

func (p *MutableStateChecksumPayload) GetDecisionStartedID() int64 {
	if !p.IsSetDecisionStartedID() {
		return MutableStateChecksumPayload_DecisionStartedID_DEFAULT
	}
	return *p.DecisionStartedID
}

var MutableStateChecksumPayload_PendingTimerStartedIDs_DEFAULT []int64

func (p *MutableStateChecksumPayload) GetPendingTimerStartedIDs() []int64 {
	return p.PendingTimerStartedIDs
}

var MutableStateChecksumPayload_PendingActivityScheduledIDs_DEFAULT []int64

func (p *MutableStateChecksumPayload) GetPendingActivityScheduledIDs() []int64 {
	return p.PendingActivityScheduledIDs
}

var MutableStateChecksumPayload_PendingSignalInitiatedIDs_DEFAULT []int64

func (p *MutableStateChecksumPayload) GetPendingSignalInitiatedIDs() []int64 {
	return p.PendingSignalInitiatedIDs
}

var MutableStateChecksumPayload_PendingReqCancelInitiatedIDs_DEFAULT []int64

func (p *MutableStateChecksumPayload) GetPendingReqCancelInitiatedIDs() []int64 {
	return p.PendingReqCancelInitiatedIDs
}

var MutableStateChecksumPayload_PendingChildInitiatedIDs_DEFAULT []int64

func (p *MutableStateChecksumPayload) GetPendingChildInitiatedIDs() []int64 {
	return p.PendingChildInitiatedIDs
}

var MutableStateChecksumPayload_StickyTaskListName_DEFAULT string

func (p *MutableStateChecksumPayload) GetStickyTaskListName() string {
	if !p.IsSetStickyTaskListName() {
		return MutableStateChecksumPayload_StickyTaskListName_DEFAULT
	}
	return *p.StickyTaskListName
}

var MutableStateChecksumPayload_VersionHistories_DEFAULT *shared.VersionHistories

func (p *MutableStateChecksumPayload) GetVersionHistories() *shared.VersionHistories {
	if !p.IsSetVersionHistories() {
		return MutableStateChecksumPayload_VersionHistories_DEFAULT
	}
	return p.VersionHistories
}
func (p *MutableStateChecksumPayload) IsSetCancelRequested() bool {
	return p.CancelRequested != nil
}

func (p *MutableStateChecksumPayload) IsSetState() bool {
	return p.State != nil
}

func (p *MutableStateChecksumPayload) IsSetCloseStatus() bool {
	return p.CloseStatus != nil
}

func (p *MutableStateChecksumPayload) IsSetLastWriteVersion() bool {
	return p.LastWriteVersion != nil
}

func (p *MutableStateChecksumPayload) IsSetLastWriteEventID() bool {
	return p.LastWriteEventID != nil
}

func (p *MutableStateChecksumPayload) IsSetLastFirstEventID() bool {
	return p.LastFirstEventID != nil
}

func (p *MutableStateChecksumPayload) IsSetNextEventID() bool {
	return p.NextEventID != nil
}

func (p *MutableStateChecksumPayload) IsSetLastProcessedEventID() bool {
	return p.LastProcessedEventID != nil
}

func (p *MutableStateChecksumPayload) IsSetSignalCount() bool {
	return p.SignalCount != nil
}

func (p *MutableStateChecksumPayload) IsSetDecisionAttempt() bool {
	return p.DecisionAttempt != nil
}

func (p *MutableStateChecksumPayload) IsSetDecisionVersion() bool {
	return p.DecisionVersion != nil
}

func (p *MutableStateChecksumPayload) IsSetDecisionScheduledID() bool {
	return p.DecisionScheduledID != nil
}

func (p *MutableStateChecksumPayload) IsSetDecisionStartedID() bool {
	return p.DecisionStartedID != nil
}

func (p *MutableStateChecksumPayload) IsSetPendingTimerStartedIDs() bool {
	return p.PendingTimerStartedIDs != nil
}

func (p *MutableStateChecksumPayload) IsSetPendingActivityScheduledIDs() bool {
	return p.PendingActivityScheduledIDs != nil
}

func (p *MutableStateChecksumPayload) IsSetPendingSignalInitiatedIDs() bool {
	return p.PendingSignalInitiatedIDs != nil
}

func (p *MutableStateChecksumPayload) IsSetPendingReqCancelInitiatedIDs() bool {
	return p.PendingReqCancelInitiatedIDs != nil
}

func (p *MutableStateChecksumPayload) IsSetPendingChildInitiatedIDs() bool {
	return p.PendingChildInitiatedIDs != nil
}

func (p *MutableStateChecksumPayload) IsSetStickyTaskListName() bool {
	return p.StickyTaskListName != nil
}

func (p *MutableStateChecksumPayload) IsSetVersionHistories() bool {
	return p.VersionHistories != nil
}

func (p *MutableStateChecksumPayload) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 15:
			if err := p.readField15(iprot); err != nil {
				return err
			}
		case 16:
			if err := p.readField16(iprot); err != nil {
				return err
			}
		case 21:
			if err := p.readField21(iprot); err != nil {
				return err
			}
		case 22:
			if err := p.readField22(iprot); err != nil {
				return err
			}
		case 23:
			if err := p.readField23(iprot); err != nil {
				return err
			}
		case 24:
			if err := p.readField24(iprot); err != nil {
				return err
			}
		case 25:
			if err := p.readField25(iprot); err != nil {
				return err
			}
		case 26:
			if err := p.readField26(iprot); err != nil {
				return err
			}
		case 35:
			if err := p.readField35(iprot); err != nil {
				return err
			}
		case 36:
			if err := p.readField36(iprot); err != nil {
				return err
			}
		case 37:
			if err := p.readField37(iprot); err != nil {
				return err
			}
		case 38:
			if err := p.readField38(iprot); err != nil {
				return err
			}
		case 45:
			if err := p.readField45(iprot); err != nil {
				return err
			}
		case 46:
			if err := p.readField46(iprot); err != nil {
				return err
			}
		case 47:
			if err := p.readField47(iprot); err != nil {
				return err
			}
		case 48:
			if err := p.readField48(iprot); err != nil {
				return err
			}
		case 49:
			if err := p.readField49(iprot); err != nil {
				return err
			}
		case 55:
			if err := p.readField55(iprot); err != nil {
				return err
			}
		case 56:
			if err := p.readField56(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.CancelRequested = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField15(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI16(); err != nil {
		return thrift.PrependError("error reading field 15: ", err)
	} else {
		p.State = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField16(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI16(); err != nil {
		return thrift.PrependError("error reading field 16: ", err)
	} else {
		p.CloseStatus = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField21(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 21: ", err)
	} else {
		p.LastWriteVersion = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField22(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 22: ", err)
	} else {
		p.LastWriteEventID = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField23(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 23: ", err)
	} else {
		p.LastFirstEventID = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField24(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 24: ", err)
	} else {
		p.NextEventID = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField25(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 25: ", err)
	} else {
		p.LastProcessedEventID = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField26(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 26: ", err)
	} else {
		p.SignalCount = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField35(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 35: ", err)
	} else {
		p.DecisionAttempt = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField36(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 36: ", err)
	} else {
		p.DecisionVersion = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField37(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 37: ", err)
	} else {
		p.DecisionScheduledID = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField38(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 38: ", err)
	} else {
		p.DecisionStartedID = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField45(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]int64, 0, size)
	p.PendingTimerStartedIDs = tSlice
	for i := 0; i < size; i++ {
		var _elem0 int64
		if v, err := iprot.ReadI64(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem0 = v
		}
		p.PendingTimerStartedIDs = append(p.PendingTimerStartedIDs, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField46(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]int64, 0, size)
	p.PendingActivityScheduledIDs = tSlice
	for i := 0; i < size; i++ {
		var _elem1 int64
		if v, err := iprot.ReadI64(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem1 = v
		}
		p.PendingActivityScheduledIDs = append(p.PendingActivityScheduledIDs, _elem1)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField47(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]int64, 0, size)
	p.PendingSignalInitiatedIDs = tSlice
	for i := 0; i < size; i++ {
		var _elem2 int64
		if v, err := iprot.ReadI64(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem2 = v
		}
		p.PendingSignalInitiatedIDs = append(p.PendingSignalInitiatedIDs, _elem2)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField48(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]int64, 0, size)
	p.PendingReqCancelInitiatedIDs = tSlice
	for i := 0; i < size; i++ {
		var _elem3 int64
		if v, err := iprot.ReadI64(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem3 = v
		}
		p.PendingReqCancelInitiatedIDs = append(p.PendingReqCancelInitiatedIDs, _elem3)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField49(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]int64, 0, size)
	p.PendingChildInitiatedIDs = tSlice
	for i := 0; i < size; i++ {
		var _elem4 int64
		if v, err := iprot.ReadI64(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem4 = v
		}
		p.PendingChildInitiatedIDs = append(p.PendingChildInitiatedIDs, _elem4)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField55(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 55: ", err)
	} else {
		p.StickyTaskListName = &v
	}
	return nil
}

func (p *MutableStateChecksumPayload) readField56(iprot thrift.TProtocol) error {
	p.VersionHistories = &shared.VersionHistories{}
	if err := p.VersionHistories.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.VersionHistories), err)
	}
	return nil
}

func (p *MutableStateChecksumPayload) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("MutableStateChecksumPayload"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField15(oprot); err != nil {
		return err
	}
	if err := p.writeField16(oprot); err != nil {
		return err
	}
	if err := p.writeField21(oprot); err != nil {
		return err
	}
	if err := p.writeField22(oprot); err != nil {
		return err
	}
	if err := p.writeField23(oprot); err != nil {
		return err
	}
	if err := p.writeField24(oprot); err != nil {
		return err
	}
	if err := p.writeField25(oprot); err != nil {
		return err
	}
	if err := p.writeField26(oprot); err != nil {
		return err
	}
	if err := p.writeField35(oprot); err != nil {
		return err
	}
	if err := p.writeField36(oprot); err != nil {
		return err
	}
	if err := p.writeField37(oprot); err != nil {
		return err
	}
	if err := p.writeField38(oprot); err != nil {
		return err
	}
	if err := p.writeField45(oprot); err != nil {
		return err
	}
	if err := p.writeField46(oprot); err != nil {
		return err
	}
	if err := p.writeField47(oprot); err != nil {
		return err
	}
	if err := p.writeField48(oprot); err != nil {
		return err
	}
	if err := p.writeField49(oprot); err != nil {
		return err
	}
	if err := p.writeField55(oprot); err != nil {
		return err
	}
	if err := p.writeField56(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MutableStateChecksumPayload) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetCancelRequested() {
		if err := oprot.WriteFieldBegin("cancelRequested", thrift.BOOL, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:cancelRequested: ", p), err)
		}
		if err := oprot.WriteBool(bool(*p.CancelRequested)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.cancelRequested (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:cancelRequested: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField15(oprot thrift.TProtocol) (err error) {
	if p.IsSetState() {
		if err := oprot.WriteFieldBegin("state", thrift.I16, 15); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 15:state: ", p), err)
		}
		if err := oprot.WriteI16(int16(*p.State)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.state (15) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 15:state: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField16(oprot thrift.TProtocol) (err error) {
	if p.IsSetCloseStatus() {
		if err := oprot.WriteFieldBegin("closeStatus", thrift.I16, 16); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 16:closeStatus: ", p), err)
		}
		if err := oprot.WriteI16(int16(*p.CloseStatus)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.closeStatus (16) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 16:closeStatus: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField21(oprot thrift.TProtocol) (err error) {
	if p.IsSetLastWriteVersion() {
		if err := oprot.WriteFieldBegin("lastWriteVersion", thrift.I64, 21); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 21:lastWriteVersion: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.LastWriteVersion)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.lastWriteVersion (21) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 21:lastWriteVersion: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField22(oprot thrift.TProtocol) (err error) {
	if p.IsSetLastWriteEventID() {
		if err := oprot.WriteFieldBegin("lastWriteEventID", thrift.I64, 22); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 22:lastWriteEventID: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.LastWriteEventID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.lastWriteEventID (22) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 22:lastWriteEventID: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField23(oprot thrift.TProtocol) (err error) {
	if p.IsSetLastFirstEventID() {
		if err := oprot.WriteFieldBegin("lastFirstEventID", thrift.I64, 23); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 23:lastFirstEventID: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.LastFirstEventID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.lastFirstEventID (23) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 23:lastFirstEventID: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField24(oprot thrift.TProtocol) (err error) {
	if p.IsSetNextEventID() {
		if err := oprot.WriteFieldBegin("nextEventID", thrift.I64, 24); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 24:nextEventID: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.NextEventID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.nextEventID (24) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 24:nextEventID: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField25(oprot thrift.TProtocol) (err error) {
	if p.IsSetLastProcessedEventID() {
		if err := oprot.WriteFieldBegin("lastProcessedEventID", thrift.I64, 25); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 25:lastProcessedEventID: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.LastProcessedEventID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.lastProcessedEventID (25) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 25:lastProcessedEventID: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField26(oprot thrift.TProtocol) (err error) {
	if p.IsSetSignalCount() {
		if err := oprot.WriteFieldBegin("signalCount", thrift.I64, 26); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 26:signalCount: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.SignalCount)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.signalCount (26) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 26:signalCount: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField35(oprot thrift.TProtocol) (err error) {
	if p.IsSetDecisionAttempt() {
		if err := oprot.WriteFieldBegin("decisionAttempt", thrift.I32, 35); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 35:decisionAttempt: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.DecisionAttempt)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.decisionAttempt (35) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 35:decisionAttempt: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField36(oprot thrift.TProtocol) (err error) {
	if p.IsSetDecisionVersion() {
		if err := oprot.WriteFieldBegin("decisionVersion", thrift.I64, 36); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 36:decisionVersion: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.DecisionVersion)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.decisionVersion (36) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 36:decisionVersion: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField37(oprot thrift.TProtocol) (err error) {
	if p.IsSetDecisionScheduledID() {
		if err := oprot.WriteFieldBegin("decisionScheduledID", thrift.I64, 37); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 37:decisionScheduledID: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.DecisionScheduledID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.decisionScheduledID (37) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 37:decisionScheduledID: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField38(oprot thrift.TProtocol) (err error) {
	if p.IsSetDecisionStartedID() {
		if err := oprot.WriteFieldBegin("decisionStartedID", thrift.I64, 38); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 38:decisionStartedID: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.DecisionStartedID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.decisionStartedID (38) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 38:decisionStartedID: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField45(oprot thrift.TProtocol) (err error) {
	if p.IsSetPendingTimerStartedIDs() {
		if err := oprot.WriteFieldBegin("pendingTimerStartedIDs", thrift.LIST, 45); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 45:pendingTimerStartedIDs: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.PendingTimerStartedIDs)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.PendingTimerStartedIDs {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 45:pendingTimerStartedIDs: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField46(oprot thrift.TProtocol) (err error) {
	if p.IsSetPendingActivityScheduledIDs() {
		if err := oprot.WriteFieldBegin("pendingActivityScheduledIDs", thrift.LIST, 46); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 46:pendingActivityScheduledIDs: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.PendingActivityScheduledIDs)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.PendingActivityScheduledIDs {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 46:pendingActivityScheduledIDs: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField47(oprot thrift.TProtocol) (err error) {
	if p.IsSetPendingSignalInitiatedIDs() {
		if err := oprot.WriteFieldBegin("pendingSignalInitiatedIDs", thrift.LIST, 47); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 47:pendingSignalInitiatedIDs: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.PendingSignalInitiatedIDs)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.PendingSignalInitiatedIDs {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 47:pendingSignalInitiatedIDs: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField48(oprot thrift.TProtocol) (err error) {
	if p.IsSetPendingReqCancelInitiatedIDs() {
		if err := oprot.WriteFieldBegin("pendingReqCancelInitiatedIDs", thrift.LIST, 48); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 48:pendingReqCancelInitiatedIDs: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.PendingReqCancelInitiatedIDs)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.PendingReqCancelInitiatedIDs {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 48:pendingReqCancelInitiatedIDs: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField49(oprot thrift.TProtocol) (err error) {
	if p.IsSetPendingChildInitiatedIDs() {
		if err := oprot.WriteFieldBegin("pendingChildInitiatedIDs", thrift.LIST, 49); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 49:pendingChildInitiatedIDs: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.PendingChildInitiatedIDs)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.PendingChildInitiatedIDs {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 49:pendingChildInitiatedIDs: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField55(oprot thrift.TProtocol) (err error) {
	if p.IsSetStickyTaskListName() {
		if err := oprot.WriteFieldBegin("stickyTaskListName", thrift.STRING, 55); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 55:stickyTaskListName: ", p), err)
		}
		if err := oprot.WriteString(string(*p.StickyTaskListName)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.stickyTaskListName (55) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 55:stickyTaskListName: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) writeField56(oprot thrift.TProtocol) (err error) {
	if p.IsSetVersionHistories() {
		if err := oprot.WriteFieldBegin("VersionHistories", thrift.STRUCT, 56); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 56:VersionHistories: ", p), err)
		}
		if err := p.VersionHistories.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.VersionHistories), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 56:VersionHistories: ", p), err)
		}
	}
	return err
}

func (p *MutableStateChecksumPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MutableStateChecksumPayload(%+v)", *p)
}
