// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"history"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  StartWorkflowExecutionResponse StartWorkflowExecution(StartWorkflowExecutionRequest startRequest)")
	fmt.Fprintln(os.Stderr, "  GetMutableStateResponse GetMutableState(GetMutableStateRequest getRequest)")
	fmt.Fprintln(os.Stderr, "  PollMutableStateResponse PollMutableState(PollMutableStateRequest pollRequest)")
	fmt.Fprintln(os.Stderr, "  ResetStickyTaskListResponse ResetStickyTaskList(ResetStickyTaskListRequest resetRequest)")
	fmt.Fprintln(os.Stderr, "  RecordDecisionTaskStartedResponse RecordDecisionTaskStarted(RecordDecisionTaskStartedRequest addRequest)")
	fmt.Fprintln(os.Stderr, "  RecordActivityTaskStartedResponse RecordActivityTaskStarted(RecordActivityTaskStartedRequest addRequest)")
	fmt.Fprintln(os.Stderr, "  RespondDecisionTaskCompletedResponse RespondDecisionTaskCompleted(RespondDecisionTaskCompletedRequest completeRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondDecisionTaskFailed(RespondDecisionTaskFailedRequest failedRequest)")
	fmt.Fprintln(os.Stderr, "  RecordActivityTaskHeartbeatResponse RecordActivityTaskHeartbeat(RecordActivityTaskHeartbeatRequest heartbeatRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskCompleted(RespondActivityTaskCompletedRequest completeRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskFailed(RespondActivityTaskFailedRequest failRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskCanceled(RespondActivityTaskCanceledRequest canceledRequest)")
	fmt.Fprintln(os.Stderr, "  void SignalWorkflowExecution(SignalWorkflowExecutionRequest signalRequest)")
	fmt.Fprintln(os.Stderr, "  StartWorkflowExecutionResponse SignalWithStartWorkflowExecution(SignalWithStartWorkflowExecutionRequest signalWithStartRequest)")
	fmt.Fprintln(os.Stderr, "  void RemoveSignalMutableState(RemoveSignalMutableStateRequest removeRequest)")
	fmt.Fprintln(os.Stderr, "  void TerminateWorkflowExecution(TerminateWorkflowExecutionRequest terminateRequest)")
	fmt.Fprintln(os.Stderr, "  ResetWorkflowExecutionResponse ResetWorkflowExecution(ResetWorkflowExecutionRequest resetRequest)")
	fmt.Fprintln(os.Stderr, "  void RequestCancelWorkflowExecution(RequestCancelWorkflowExecutionRequest cancelRequest)")
	fmt.Fprintln(os.Stderr, "  void ScheduleDecisionTask(ScheduleDecisionTaskRequest scheduleRequest)")
	fmt.Fprintln(os.Stderr, "  void RecordChildExecutionCompleted(RecordChildExecutionCompletedRequest completionRequest)")
	fmt.Fprintln(os.Stderr, "  DescribeWorkflowExecutionResponse DescribeWorkflowExecution(DescribeWorkflowExecutionRequest describeRequest)")
	fmt.Fprintln(os.Stderr, "  void ReplicateEventsV2(ReplicateEventsV2Request replicateV2Request)")
	fmt.Fprintln(os.Stderr, "  void SyncShardStatus(SyncShardStatusRequest syncShardStatusRequest)")
	fmt.Fprintln(os.Stderr, "  void SyncActivity(SyncActivityRequest syncActivityRequest)")
	fmt.Fprintln(os.Stderr, "  DescribeMutableStateResponse DescribeMutableState(DescribeMutableStateRequest request)")
	fmt.Fprintln(os.Stderr, "  DescribeHistoryHostResponse DescribeHistoryHost(DescribeHistoryHostRequest request)")
	fmt.Fprintln(os.Stderr, "  void CloseShard(CloseShardRequest request)")
	fmt.Fprintln(os.Stderr, "  void RemoveTask(RemoveTaskRequest request)")
	fmt.Fprintln(os.Stderr, "  void ResetQueue(ResetQueueRequest request)")
	fmt.Fprintln(os.Stderr, "  DescribeQueueResponse DescribeQueue(DescribeQueueRequest request)")
	fmt.Fprintln(os.Stderr, "  GetReplicationMessagesResponse GetReplicationMessages(GetReplicationMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  GetDLQReplicationMessagesResponse GetDLQReplicationMessages(GetDLQReplicationMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  QueryWorkflowResponse QueryWorkflow(QueryWorkflowRequest queryRequest)")
	fmt.Fprintln(os.Stderr, "  void ReapplyEvents(ReapplyEventsRequest reapplyEventsRequest)")
	fmt.Fprintln(os.Stderr, "  void RefreshWorkflowTasks(RefreshWorkflowTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  ReadDLQMessagesResponse ReadDLQMessages(ReadDLQMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  void PurgeDLQMessages(PurgeDLQMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  MergeDLQMessagesResponse MergeDLQMessages(MergeDLQMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  CountHistoryTaskDLQTasksResponse CountHistoryTaskDLQTasks(CountHistoryTaskDLQTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  GetHistoryTaskDLQAckLevelsResponse GetHistoryTaskDLQAckLevels(GetHistoryTaskDLQAckLevelsRequest request)")
	fmt.Fprintln(os.Stderr, "  ReadHistoryTaskDLQTasksResponse ReadHistoryTaskDLQTasks(ReadHistoryTaskDLQTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  void NotifyFailoverMarkers(NotifyFailoverMarkersRequest request)")
	fmt.Fprintln(os.Stderr, "  GetCrossClusterTasksResponse GetCrossClusterTasks(GetCrossClusterTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  RespondCrossClusterTasksCompletedResponse RespondCrossClusterTasksCompleted(RespondCrossClusterTasksCompletedRequest request)")
	fmt.Fprintln(os.Stderr, "  GetFailoverInfoResponse GetFailoverInfo(GetFailoverInfoRequest request)")
	fmt.Fprintln(os.Stderr, "  RatelimitUpdateResponse RatelimitUpdate(RatelimitUpdateRequest request)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := history.NewHistoryServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "StartWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "StartWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg116 := flag.Arg(1)
		mbTrans117 := thrift.NewTMemoryBufferLen(len(arg116))
		defer mbTrans117.Close()
		_, err118 := mbTrans117.WriteString(arg116)
		if err118 != nil {
			Usage()
			return
		}
		factory119 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt120 := factory119.GetProtocol(mbTrans117)
		argvalue0 := history.NewStartWorkflowExecutionRequest()
		err121 := argvalue0.Read(jsProt120)
		if err121 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.StartWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "GetMutableState":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetMutableState requires 1 args")
			flag.Usage()
		}
		arg122 := flag.Arg(1)
		mbTrans123 := thrift.NewTMemoryBufferLen(len(arg122))
		defer mbTrans123.Close()
		_, err124 := mbTrans123.WriteString(arg122)
		if err124 != nil {
			Usage()
			return
		}
		factory125 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt126 := factory125.GetProtocol(mbTrans123)
		argvalue0 := history.NewGetMutableStateRequest()
		err127 := argvalue0.Read(jsProt126)
		if err127 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetMutableState(value0))
		fmt.Print("\n")
		break
	case "PollMutableState":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "PollMutableState requires 1 args")
			flag.Usage()
		}
		arg128 := flag.Arg(1)
		mbTrans129 := thrift.NewTMemoryBufferLen(len(arg128))
		defer mbTrans129.Close()
		_, err130 := mbTrans129.WriteString(arg128)
		if err130 != nil {
			Usage()
			return
		}
		factory131 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt132 := factory131.GetProtocol(mbTrans129)
		argvalue0 := history.NewPollMutableStateRequest()
		err133 := argvalue0.Read(jsProt132)
		if err133 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.PollMutableState(value0))
		fmt.Print("\n")
		break
	case "ResetStickyTaskList":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ResetStickyTaskList requires 1 args")
			flag.Usage()
		}
		arg134 := flag.Arg(1)
		mbTrans135 := thrift.NewTMemoryBufferLen(len(arg134))
		defer mbTrans135.Close()
		_, err136 := mbTrans135.WriteString(arg134)
		if err136 != nil {
			Usage()
			return
		}
		factory137 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt138 := factory137.GetProtocol(mbTrans135)
		argvalue0 := history.NewResetStickyTaskListRequest()
		err139 := argvalue0.Read(jsProt138)
		if err139 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ResetStickyTaskList(value0))
		fmt.Print("\n")
		break
	case "RecordDecisionTaskStarted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RecordDecisionTaskStarted requires 1 args")
			flag.Usage()
		}
		arg140 := flag.Arg(1)
		mbTrans141 := thrift.NewTMemoryBufferLen(len(arg140))
		defer mbTrans141.Close()
		_, err142 := mbTrans141.WriteString(arg140)
		if err142 != nil {
			Usage()
			return
		}
		factory143 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt144 := factory143.GetProtocol(mbTrans141)
		argvalue0 := history.NewRecordDecisionTaskStartedRequest()
		err145 := argvalue0.Read(jsProt144)
		if err145 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RecordDecisionTaskStarted(value0))
		fmt.Print("\n")
		break
	case "RecordActivityTaskStarted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RecordActivityTaskStarted requires 1 args")
			flag.Usage()
		}
		arg146 := flag.Arg(1)
		mbTrans147 := thrift.NewTMemoryBufferLen(len(arg146))
		defer mbTrans147.Close()
		_, err148 := mbTrans147.WriteString(arg146)
		if err148 != nil {
			Usage()
			return
		}
		factory149 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt150 := factory149.GetProtocol(mbTrans147)
		argvalue0 := history.NewRecordActivityTaskStartedRequest()
		err151 := argvalue0.Read(jsProt150)
		if err151 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RecordActivityTaskStarted(value0))
		fmt.Print("\n")
		break
	case "RespondDecisionTaskCompleted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondDecisionTaskCompleted requires 1 args")
			flag.Usage()
		}
		arg152 := flag.Arg(1)
		mbTrans153 := thrift.NewTMemoryBufferLen(len(arg152))
		defer mbTrans153.Close()
		_, err154 := mbTrans153.WriteString(arg152)
		if err154 != nil {
			Usage()
			return
		}
		factory155 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt156 := factory155.GetProtocol(mbTrans153)
		argvalue0 := history.NewRespondDecisionTaskCompletedRequest()
		err157 := argvalue0.Read(jsProt156)
		if err157 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondDecisionTaskCompleted(value0))
		fmt.Print("\n")
		break
	case "RespondDecisionTaskFailed":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondDecisionTaskFailed requires 1 args")
			flag.Usage()
		}
		arg158 := flag.Arg(1)
		mbTrans159 := thrift.NewTMemoryBufferLen(len(arg158))
		defer mbTrans159.Close()
		_, err160 := mbTrans159.WriteString(arg158)
		if err160 != nil {
			Usage()
			return
		}
		factory161 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt162 := factory161.GetProtocol(mbTrans159)
		argvalue0 := history.NewRespondDecisionTaskFailedRequest()
		err163 := argvalue0.Read(jsProt162)
		if err163 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondDecisionTaskFailed(value0))
		fmt.Print("\n")
		break
	case "RecordActivityTaskHeartbeat":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RecordActivityTaskHeartbeat requires 1 args")
			flag.Usage()
		}
		arg164 := flag.Arg(1)
		mbTrans165 := thrift.NewTMemoryBufferLen(len(arg164))
		defer mbTrans165.Close()
		_, err166 := mbTrans165.WriteString(arg164)
		if err166 != nil {
			Usage()
			return
		}
		factory167 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt168 := factory167.GetProtocol(mbTrans165)
		argvalue0 := history.NewRecordActivityTaskHeartbeatRequest()
		err169 := argvalue0.Read(jsProt168)
		if err169 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RecordActivityTaskHeartbeat(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskCompleted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskCompleted requires 1 args")
			flag.Usage()
		}
		arg170 := flag.Arg(1)
		mbTrans171 := thrift.NewTMemoryBufferLen(len(arg170))
		defer mbTrans171.Close()
		_, err172 := mbTrans171.WriteString(arg170)
		if err172 != nil {
			Usage()
			return
		}
		factory173 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt174 := factory173.GetProtocol(mbTrans171)
		argvalue0 := history.NewRespondActivityTaskCompletedRequest()
		err175 := argvalue0.Read(jsProt174)
		if err175 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskCompleted(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskFailed":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskFailed requires 1 args")
			flag.Usage()
		}
		arg176 := flag.Arg(1)
		mbTrans177 := thrift.NewTMemoryBufferLen(len(arg176))
		defer mbTrans177.Close()
		_, err178 := mbTrans177.WriteString(arg176)
		if err178 != nil {
			Usage()
			return
		}
		factory179 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt180 := factory179.GetProtocol(mbTrans177)
		argvalue0 := history.NewRespondActivityTaskFailedRequest()
		err181 := argvalue0.Read(jsProt180)
		if err181 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskFailed(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskCanceled":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskCanceled requires 1 args")
			flag.Usage()
		}
		arg182 := flag.Arg(1)
		mbTrans183 := thrift.NewTMemoryBufferLen(len(arg182))
		defer mbTrans183.Close()
		_, err184 := mbTrans183.WriteString(arg182)
		if err184 != nil {
			Usage()
			return
		}
		factory185 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt186 := factory185.GetProtocol(mbTrans183)
		argvalue0 := history.NewRespondActivityTaskCanceledRequest()
		err187 := argvalue0.Read(jsProt186)
		if err187 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskCanceled(value0))
		fmt.Print("\n")
		break
	case "SignalWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SignalWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg188 := flag.Arg(1)
		mbTrans189 := thrift.NewTMemoryBufferLen(len(arg188))
		defer mbTrans189.Close()
		_, err190 := mbTrans189.WriteString(arg188)
		if err190 != nil {
			Usage()
			return
		}
		factory191 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt192 := factory191.GetProtocol(mbTrans189)
		argvalue0 := history.NewSignalWorkflowExecutionRequest()
		err193 := argvalue0.Read(jsProt192)
		if err193 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SignalWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "SignalWithStartWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SignalWithStartWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg194 := flag.Arg(1)
		mbTrans195 := thrift.NewTMemoryBufferLen(len(arg194))
		defer mbTrans195.Close()
		_, err196 := mbTrans195.WriteString(arg194)
		if err196 != nil {
			Usage()
			return
		}
		factory197 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt198 := factory197.GetProtocol(mbTrans195)
		argvalue0 := history.NewSignalWithStartWorkflowExecutionRequest()
		err199 := argvalue0.Read(jsProt198)
		if err199 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SignalWithStartWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "RemoveSignalMutableState":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RemoveSignalMutableState requires 1 args")
			flag.Usage()
		}
		arg200 := flag.Arg(1)
		mbTrans201 := thrift.NewTMemoryBufferLen(len(arg200))
		defer mbTrans201.Close()
		_, err202 := mbTrans201.WriteString(arg200)
		if err202 != nil {
			Usage()
			return
		}
		factory203 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt204 := factory203.GetProtocol(mbTrans201)
		argvalue0 := history.NewRemoveSignalMutableStateRequest()
		err205 := argvalue0.Read(jsProt204)
		if err205 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RemoveSignalMutableState(value0))
		fmt.Print("\n")
		break
	case "TerminateWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "TerminateWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg206 := flag.Arg(1)
		mbTrans207 := thrift.NewTMemoryBufferLen(len(arg206))
		defer mbTrans207.Close()
		_, err208 := mbTrans207.WriteString(arg206)
		if err208 != nil {
			Usage()
			return
		}
		factory209 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt210 := factory209.GetProtocol(mbTrans207)
		argvalue0 := history.NewTerminateWorkflowExecutionRequest()
		err211 := argvalue0.Read(jsProt210)
		if err211 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.TerminateWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "ResetWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ResetWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg212 := flag.Arg(1)
		mbTrans213 := thrift.NewTMemoryBufferLen(len(arg212))
		defer mbTrans213.Close()
		_, err214 := mbTrans213.WriteString(arg212)
		if err214 != nil {
			Usage()
			return
		}
		factory215 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt216 := factory215.GetProtocol(mbTrans213)
		argvalue0 := history.NewResetWorkflowExecutionRequest()
		err217 := argvalue0.Read(jsProt216)
		if err217 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ResetWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "RequestCancelWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RequestCancelWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg218 := flag.Arg(1)
		mbTrans219 := thrift.NewTMemoryBufferLen(len(arg218))
		defer mbTrans219.Close()
		_, err220 := mbTrans219.WriteString(arg218)
		if err220 != nil {
			Usage()
			return
		}
		factory221 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt222 := factory221.GetProtocol(mbTrans219)
		argvalue0 := history.NewRequestCancelWorkflowExecutionRequest()
		err223 := argvalue0.Read(jsProt222)
		if err223 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RequestCancelWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "ScheduleDecisionTask":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ScheduleDecisionTask requires 1 args")
			flag.Usage()
		}
		arg224 := flag.Arg(1)
		mbTrans225 := thrift.NewTMemoryBufferLen(len(arg224))
		defer mbTrans225.Close()
		_, err226 := mbTrans225.WriteString(arg224)
		if err226 != nil {
			Usage()
			return
		}
		factory227 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt228 := factory227.GetProtocol(mbTrans225)
		argvalue0 := history.NewScheduleDecisionTaskRequest()
		err229 := argvalue0.Read(jsProt228)
		if err229 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ScheduleDecisionTask(value0))
		fmt.Print("\n")
		break
	case "RecordChildExecutionCompleted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RecordChildExecutionCompleted requires 1 args")
			flag.Usage()
		}
		arg230 := flag.Arg(1)
		mbTrans231 := thrift.NewTMemoryBufferLen(len(arg230))
		defer mbTrans231.Close()
		_, err232 := mbTrans231.WriteString(arg230)
		if err232 != nil {
			Usage()
			return
		}
		factory233 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt234 := factory233.GetProtocol(mbTrans231)
		argvalue0 := history.NewRecordChildExecutionCompletedRequest()
		err235 := argvalue0.Read(jsProt234)
		if err235 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RecordChildExecutionCompleted(value0))
		fmt.Print("\n")
		break
	case "DescribeWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg236 := flag.Arg(1)
		mbTrans237 := thrift.NewTMemoryBufferLen(len(arg236))
		defer mbTrans237.Close()
		_, err238 := mbTrans237.WriteString(arg236)
		if err238 != nil {
			Usage()
			return
		}
		factory239 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt240 := factory239.GetProtocol(mbTrans237)
		argvalue0 := history.NewDescribeWorkflowExecutionRequest()
		err241 := argvalue0.Read(jsProt240)
		if err241 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "ReplicateEventsV2":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ReplicateEventsV2 requires 1 args")
			flag.Usage()
		}
		arg242 := flag.Arg(1)
		mbTrans243 := thrift.NewTMemoryBufferLen(len(arg242))
		defer mbTrans243.Close()
		_, err244 := mbTrans243.WriteString(arg242)
		if err244 != nil {
			Usage()
			return
		}
		factory245 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt246 := factory245.GetProtocol(mbTrans243)
		argvalue0 := history.NewReplicateEventsV2Request()
		err247 := argvalue0.Read(jsProt246)
		if err247 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ReplicateEventsV2(value0))
		fmt.Print("\n")
		break
	case "SyncShardStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SyncShardStatus requires 1 args")
			flag.Usage()
		}
		arg248 := flag.Arg(1)
		mbTrans249 := thrift.NewTMemoryBufferLen(len(arg248))
		defer mbTrans249.Close()
		_, err250 := mbTrans249.WriteString(arg248)
		if err250 != nil {
			Usage()
			return
		}
		factory251 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt252 := factory251.GetProtocol(mbTrans249)
		argvalue0 := history.NewSyncShardStatusRequest()
		err253 := argvalue0.Read(jsProt252)
		if err253 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SyncShardStatus(value0))
		fmt.Print("\n")
		break
	case "SyncActivity":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SyncActivity requires 1 args")
			flag.Usage()
		}
		arg254 := flag.Arg(1)
		mbTrans255 := thrift.NewTMemoryBufferLen(len(arg254))
		defer mbTrans255.Close()
		_, err256 := mbTrans255.WriteString(arg254)
		if err256 != nil {
			Usage()
			return
		}
		factory257 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt258 := factory257.GetProtocol(mbTrans255)
		argvalue0 := history.NewSyncActivityRequest()
		err259 := argvalue0.Read(jsProt258)
		if err259 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SyncActivity(value0))
		fmt.Print("\n")
		break
	case "DescribeMutableState":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeMutableState requires 1 args")
			flag.Usage()
		}
		arg260 := flag.Arg(1)
		mbTrans261 := thrift.NewTMemoryBufferLen(len(arg260))
		defer mbTrans261.Close()
		_, err262 := mbTrans261.WriteString(arg260)
		if err262 != nil {
			Usage()
			return
		}
		factory263 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt264 := factory263.GetProtocol(mbTrans261)
		argvalue0 := history.NewDescribeMutableStateRequest()
		err265 := argvalue0.Read(jsProt264)
		if err265 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeMutableState(value0))
		fmt.Print("\n")
		break
	case "DescribeHistoryHost":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeHistoryHost requires 1 args")
			flag.Usage()
		}
		arg266 := flag.Arg(1)
		mbTrans267 := thrift.NewTMemoryBufferLen(len(arg266))
		defer mbTrans267.Close()
		_, err268 := mbTrans267.WriteString(arg266)
		if err268 != nil {
			Usage()
			return
		}
		factory269 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt270 := factory269.GetProtocol(mbTrans267)
		argvalue0 := history.NewDescribeHistoryHostRequest()
		err271 := argvalue0.Read(jsProt270)
		if err271 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeHistoryHost(value0))
		fmt.Print("\n")
		break
	case "CloseShard":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CloseShard requires 1 args")
			flag.Usage()
		}
		arg272 := flag.Arg(1)
		mbTrans273 := thrift.NewTMemoryBufferLen(len(arg272))
		defer mbTrans273.Close()
		_, err274 := mbTrans273.WriteString(arg272)
		if err274 != nil {
			Usage()
			return
		}
		factory275 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt276 := factory275.GetProtocol(mbTrans273)
		argvalue0 := history.NewCloseShardRequest()
		err277 := argvalue0.Read(jsProt276)
		if err277 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CloseShard(value0))
		fmt.Print("\n")
		break
	case "RemoveTask":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RemoveTask requires 1 args")
			flag.Usage()
		}
		arg278 := flag.Arg(1)
		mbTrans279 := thrift.NewTMemoryBufferLen(len(arg278))
		defer mbTrans279.Close()
		_, err280 := mbTrans279.WriteString(arg278)
		if err280 != nil {
			Usage()
			return
		}
		factory281 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt282 := factory281.GetProtocol(mbTrans279)
		argvalue0 := history.NewRemoveTaskRequest()
		err283 := argvalue0.Read(jsProt282)
		if err283 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RemoveTask(value0))
		fmt.Print("\n")
		break
	case "ResetQueue":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ResetQueue requires 1 args")
			flag.Usage()
		}
		arg284 := flag.Arg(1)
		mbTrans285 := thrift.NewTMemoryBufferLen(len(arg284))
		defer mbTrans285.Close()
		_, err286 := mbTrans285.WriteString(arg284)
		if err286 != nil {
			Usage()
			return
		}
		factory287 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt288 := factory287.GetProtocol(mbTrans285)
		argvalue0 := history.NewResetQueueRequest()
		err289 := argvalue0.Read(jsProt288)
		if err289 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ResetQueue(value0))
		fmt.Print("\n")
		break
	case "DescribeQueue":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeQueue requires 1 args")
			flag.Usage()
		}
		arg290 := flag.Arg(1)
		mbTrans291 := thrift.NewTMemoryBufferLen(len(arg290))
		defer mbTrans291.Close()
		_, err292 := mbTrans291.WriteString(arg290)
		if err292 != nil {
			Usage()
			return
		}
		factory293 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt294 := factory293.GetProtocol(mbTrans291)
		argvalue0 := history.NewDescribeQueueRequest()
		err295 := argvalue0.Read(jsProt294)
		if err295 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeQueue(value0))
		fmt.Print("\n")
		break
	case "GetReplicationMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetReplicationMessages requires 1 args")
			flag.Usage()
		}
		arg296 := flag.Arg(1)
		mbTrans297 := thrift.NewTMemoryBufferLen(len(arg296))
		defer mbTrans297.Close()
		_, err298 := mbTrans297.WriteString(arg296)
		if err298 != nil {
			Usage()
			return
		}
		factory299 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt300 := factory299.GetProtocol(mbTrans297)
		argvalue0 := history.NewGetReplicationMessagesRequest()
		err301 := argvalue0.Read(jsProt300)
		if err301 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetReplicationMessages(value0))
		fmt.Print("\n")
		break
	case "GetDLQReplicationMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDLQReplicationMessages requires 1 args")
			flag.Usage()
		}
		arg302 := flag.Arg(1)
		mbTrans303 := thrift.NewTMemoryBufferLen(len(arg302))
		defer mbTrans303.Close()
		_, err304 := mbTrans303.WriteString(arg302)
		if err304 != nil {
			Usage()
			return
		}
		factory305 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt306 := factory305.GetProtocol(mbTrans303)
		argvalue0 := history.NewGetDLQReplicationMessagesRequest()
		err307 := argvalue0.Read(jsProt306)
		if err307 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetDLQReplicationMessages(value0))
		fmt.Print("\n")
		break
	case "QueryWorkflow":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryWorkflow requires 1 args")
			flag.Usage()
		}
		arg308 := flag.Arg(1)
		mbTrans309 := thrift.NewTMemoryBufferLen(len(arg308))
		defer mbTrans309.Close()
		_, err310 := mbTrans309.WriteString(arg308)
		if err310 != nil {
			Usage()
			return
		}
		factory311 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt312 := factory311.GetProtocol(mbTrans309)
		argvalue0 := history.NewQueryWorkflowRequest()
		err313 := argvalue0.Read(jsProt312)
		if err313 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryWorkflow(value0))
		fmt.Print("\n")
		break
	case "ReapplyEvents":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ReapplyEvents requires 1 args")
			flag.Usage()
		}
		arg314 := flag.Arg(1)
		mbTrans315 := thrift.NewTMemoryBufferLen(len(arg314))
		defer mbTrans315.Close()
		_, err316 := mbTrans315.WriteString(arg314)
		if err316 != nil {
			Usage()
			return
		}
		factory317 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt318 := factory317.GetProtocol(mbTrans315)
		argvalue0 := history.NewReapplyEventsRequest()
		err319 := argvalue0.Read(jsProt318)
		if err319 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ReapplyEvents(value0))
		fmt.Print("\n")
		break
	case "RefreshWorkflowTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RefreshWorkflowTasks requires 1 args")
			flag.Usage()
		}
		arg320 := flag.Arg(1)
		mbTrans321 := thrift.NewTMemoryBufferLen(len(arg320))
		defer mbTrans321.Close()
		_, err322 := mbTrans321.WriteString(arg320)
		if err322 != nil {
			Usage()
			return
		}
		factory323 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt324 := factory323.GetProtocol(mbTrans321)
		argvalue0 := history.NewRefreshWorkflowTasksRequest()
		err325 := argvalue0.Read(jsProt324)
		if err325 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RefreshWorkflowTasks(value0))
		fmt.Print("\n")
		break
	case "ReadDLQMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ReadDLQMessages requires 1 args")
			flag.Usage()
		}
		arg326 := flag.Arg(1)
		mbTrans327 := thrift.NewTMemoryBufferLen(len(arg326))
		defer mbTrans327.Close()
		_, err328 := mbTrans327.WriteString(arg326)
		if err328 != nil {
			Usage()
			return
		}
		factory329 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt330 := factory329.GetProtocol(mbTrans327)
		argvalue0 := history.NewReadDLQMessagesRequest()
		err331 := argvalue0.Read(jsProt330)
		if err331 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ReadDLQMessages(value0))
		fmt.Print("\n")
		break
	case "PurgeDLQMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "PurgeDLQMessages requires 1 args")
			flag.Usage()
		}
		arg332 := flag.Arg(1)
		mbTrans333 := thrift.NewTMemoryBufferLen(len(arg332))
		defer mbTrans333.Close()
		_, err334 := mbTrans333.WriteString(arg332)
		if err334 != nil {
			Usage()
			return
		}
		factory335 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt336 := factory335.GetProtocol(mbTrans333)
		argvalue0 := history.NewPurgeDLQMessagesRequest()
		err337 := argvalue0.Read(jsProt336)
		if err337 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.PurgeDLQMessages(value0))
		fmt.Print("\n")
		break
	case "MergeDLQMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MergeDLQMessages requires 1 args")
			flag.Usage()
		}
		arg338 := flag.Arg(1)
		mbTrans339 := thrift.NewTMemoryBufferLen(len(arg338))
		defer mbTrans339.Close()
		_, err340 := mbTrans339.WriteString(arg338)
		if err340 != nil {
			Usage()
			return
		}
		factory341 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt342 := factory341.GetProtocol(mbTrans339)
		argvalue0 := history.NewMergeDLQMessagesRequest()
		err343 := argvalue0.Read(jsProt342)
		if err343 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.MergeDLQMessages(value0))
		fmt.Print("\n")
		break
	case "CountHistoryTaskDLQTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CountHistoryTaskDLQTasks requires 1 args")
			flag.Usage()
		}
		arg344 := flag.Arg(1)
		mbTrans345 := thrift.NewTMemoryBufferLen(len(arg344))
		defer mbTrans345.Close()
		_, err346 := mbTrans345.WriteString(arg344)
		if err346 != nil {
			Usage()
			return
		}
		factory347 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt348 := factory347.GetProtocol(mbTrans345)
		argvalue0 := history.NewCountHistoryTaskDLQTasksRequest()
		err349 := argvalue0.Read(jsProt348)
		if err349 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountHistoryTaskDLQTasks(value0))
		fmt.Print("\n")
		break
	case "GetHistoryTaskDLQAckLevels":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetHistoryTaskDLQAckLevels requires 1 args")
			flag.Usage()
		}
		arg350 := flag.Arg(1)
		mbTrans351 := thrift.NewTMemoryBufferLen(len(arg350))
		defer mbTrans351.Close()
		_, err352 := mbTrans351.WriteString(arg350)
		if err352 != nil {
			Usage()
			return
		}
		factory353 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt354 := factory353.GetProtocol(mbTrans351)
		argvalue0 := history.NewGetHistoryTaskDLQAckLevelsRequest()
		err355 := argvalue0.Read(jsProt354)
		if err355 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetHistoryTaskDLQAckLevels(value0))
		fmt.Print("\n")
		break
	case "ReadHistoryTaskDLQTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ReadHistoryTaskDLQTasks requires 1 args")
			flag.Usage()
		}
		arg356 := flag.Arg(1)
		mbTrans357 := thrift.NewTMemoryBufferLen(len(arg356))
		defer mbTrans357.Close()
		_, err358 := mbTrans357.WriteString(arg356)
		if err358 != nil {
			Usage()
			return
		}
		factory359 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt360 := factory359.GetProtocol(mbTrans357)
		argvalue0 := history.NewReadHistoryTaskDLQTasksRequest()
		err361 := argvalue0.Read(jsProt360)
		if err361 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ReadHistoryTaskDLQTasks(value0))
		fmt.Print("\n")
		break
	case "NotifyFailoverMarkers":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "NotifyFailoverMarkers requires 1 args")
			flag.Usage()
		}
		arg362 := flag.Arg(1)
		mbTrans363 := thrift.NewTMemoryBufferLen(len(arg362))
		defer mbTrans363.Close()
		_, err364 := mbTrans363.WriteString(arg362)
		if err364 != nil {
			Usage()
			return
		}
		factory365 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt366 := factory365.GetProtocol(mbTrans363)
		argvalue0 := history.NewNotifyFailoverMarkersRequest()
		err367 := argvalue0.Read(jsProt366)
		if err367 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.NotifyFailoverMarkers(value0))
		fmt.Print("\n")
		break
	case "GetCrossClusterTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetCrossClusterTasks requires 1 args")
			flag.Usage()
		}
		arg368 := flag.Arg(1)
		mbTrans369 := thrift.NewTMemoryBufferLen(len(arg368))
		defer mbTrans369.Close()
		_, err370 := mbTrans369.WriteString(arg368)
		if err370 != nil {
			Usage()
			return
		}
		factory371 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt372 := factory371.GetProtocol(mbTrans369)
		argvalue0 := history.NewGetCrossClusterTasksRequest()
		err373 := argvalue0.Read(jsProt372)
		if err373 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetCrossClusterTasks(value0))
		fmt.Print("\n")
		break
	case "RespondCrossClusterTasksCompleted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondCrossClusterTasksCompleted requires 1 args")
			flag.Usage()
		}
		arg374 := flag.Arg(1)
		mbTrans375 := thrift.NewTMemoryBufferLen(len(arg374))
		defer mbTrans375.Close()
		_, err376 := mbTrans375.WriteString(arg374)
		if err376 != nil {
			Usage()
			return
		}
		factory377 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt378 := factory377.GetProtocol(mbTrans375)
		argvalue0 := history.NewRespondCrossClusterTasksCompletedRequest()
		err379 := argvalue0.Read(jsProt378)
		if err379 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondCrossClusterTasksCompleted(value0))
		fmt.Print("\n")
		break
	case "GetFailoverInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetFailoverInfo requires 1 args")
			flag.Usage()
		}
		arg380 := flag.Arg(1)
		mbTrans381 := thrift.NewTMemoryBufferLen(len(arg380))
		defer mbTrans381.Close()
		_, err382 := mbTrans381.WriteString(arg380)
		if err382 != nil {
			Usage()
			return
		}
		factory383 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt384 := factory383.GetProtocol(mbTrans381)
		argvalue0 := history.NewGetFailoverInfoRequest()
		err385 := argvalue0.Read(jsProt384)
		if err385 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetFailoverInfo(value0))
		fmt.Print("\n")
		break
	case "RatelimitUpdate":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RatelimitUpdate requires 1 args")
			flag.Usage()
		}
		arg386 := flag.Arg(1)
		mbTrans387 := thrift.NewTMemoryBufferLen(len(arg386))
		defer mbTrans387.Close()
		_, err388 := mbTrans387.WriteString(arg386)
		if err388 != nil {
			Usage()
			return
		}
		factory389 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt390 := factory389.GetProtocol(mbTrans387)
		argvalue0 := history.NewRatelimitUpdateRequest()
		err391 := argvalue0.Read(jsProt390)
		if err391 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RatelimitUpdate(value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
