// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package history

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"replicator"
	"shared"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__
var _ = replicator.GoUnusedProtection__

const WeightedRatelimitUsageAnyType = "cadence:loadbalanced:update_request"
const WeightedRatelimitQuotasAnyType = "cadence:loadbalanced:update_response"
const WeightedRatelimitUsageQuotasAnyType = "cadence:loadbalanced:update_response_used"

func init() {
}
