// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package config

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"shared"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__
var GoUnusedProtection__ int

// Attributes:
//   - SchemaVersion
//   - Entries
type DynamicConfigBlob struct {
	// unused fields # 1 to 9
	SchemaVersion *int64 `thrift:"schemaVersion,10" json:"schemaVersion,omitempty"`
	// unused fields # 11 to 19
	Entries []*DynamicConfigEntry `thrift:"entries,20" json:"entries,omitempty"`
}

func NewDynamicConfigBlob() *DynamicConfigBlob {
	return &DynamicConfigBlob{}
}

var DynamicConfigBlob_SchemaVersion_DEFAULT int64

func (p *DynamicConfigBlob) GetSchemaVersion() int64 {
	if !p.IsSetSchemaVersion() {
		return DynamicConfigBlob_SchemaVersion_DEFAULT
	}
	return *p.SchemaVersion
}

var DynamicConfigBlob_Entries_DEFAULT []*DynamicConfigEntry

func (p *DynamicConfigBlob) GetEntries() []*DynamicConfigEntry {
	return p.Entries
}
func (p *DynamicConfigBlob) IsSetSchemaVersion() bool {
	return p.SchemaVersion != nil
}

func (p *DynamicConfigBlob) IsSetEntries() bool {
	return p.Entries != nil
}

func (p *DynamicConfigBlob) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DynamicConfigBlob) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.SchemaVersion = &v
	}
	return nil
}

func (p *DynamicConfigBlob) readField20(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*DynamicConfigEntry, 0, size)
	p.Entries = tSlice
	for i := 0; i < size; i++ {
		_elem0 := &DynamicConfigEntry{}
		if err := _elem0.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem0), err)
		}
		p.Entries = append(p.Entries, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *DynamicConfigBlob) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("DynamicConfigBlob"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DynamicConfigBlob) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetSchemaVersion() {
		if err := oprot.WriteFieldBegin("schemaVersion", thrift.I64, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:schemaVersion: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.SchemaVersion)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.schemaVersion (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:schemaVersion: ", p), err)
		}
	}
	return err
}

func (p *DynamicConfigBlob) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetEntries() {
		if err := oprot.WriteFieldBegin("entries", thrift.LIST, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:entries: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Entries)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Entries {
			if err := v.Write(oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:entries: ", p), err)
		}
	}
	return err
}

func (p *DynamicConfigBlob) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DynamicConfigBlob(%+v)", *p)
}

// Attributes:
//   - Name
//   - Values
type DynamicConfigEntry struct {
	// unused fields # 1 to 9
	Name *string `thrift:"name,10" json:"name,omitempty"`
	// unused fields # 11 to 19
	Values []*DynamicConfigValue `thrift:"values,20" json:"values,omitempty"`
}

func NewDynamicConfigEntry() *DynamicConfigEntry {
	return &DynamicConfigEntry{}
}

var DynamicConfigEntry_Name_DEFAULT string

func (p *DynamicConfigEntry) GetName() string {
	if !p.IsSetName() {
		return DynamicConfigEntry_Name_DEFAULT
	}
	return *p.Name
}

var DynamicConfigEntry_Values_DEFAULT []*DynamicConfigValue

func (p *DynamicConfigEntry) GetValues() []*DynamicConfigValue {
	return p.Values
}
func (p *DynamicConfigEntry) IsSetName() bool {
	return p.Name != nil
}

func (p *DynamicConfigEntry) IsSetValues() bool {
	return p.Values != nil
}

func (p *DynamicConfigEntry) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DynamicConfigEntry) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.Name = &v
	}
	return nil
}

func (p *DynamicConfigEntry) readField20(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*DynamicConfigValue, 0, size)
	p.Values = tSlice
	for i := 0; i < size; i++ {
		_elem1 := &DynamicConfigValue{}
		if err := _elem1.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem1), err)
		}
		p.Values = append(p.Values, _elem1)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *DynamicConfigEntry) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("DynamicConfigEntry"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DynamicConfigEntry) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetName() {
		if err := oprot.WriteFieldBegin("name", thrift.STRING, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:name: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Name)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.name (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:name: ", p), err)
		}
	}
	return err
}

func (p *DynamicConfigEntry) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetValues() {
		if err := oprot.WriteFieldBegin("values", thrift.LIST, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:values: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Values)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Values {
			if err := v.Write(oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:values: ", p), err)
		}
	}
	return err
}

func (p *DynamicConfigEntry) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DynamicConfigEntry(%+v)", *p)
}

// Attributes:
//   - Value
//   - Filters
type DynamicConfigValue struct {
	// unused fields # 1 to 9
	Value *shared.DataBlob `thrift:"value,10" json:"value,omitempty"`
	// unused fields # 11 to 19
	Filters []*DynamicConfigFilter `thrift:"filters,20" json:"filters,omitempty"`
}

func NewDynamicConfigValue() *DynamicConfigValue {
	return &DynamicConfigValue{}
}

var DynamicConfigValue_Value_DEFAULT *shared.DataBlob

func (p *DynamicConfigValue) GetValue() *shared.DataBlob {
	if !p.IsSetValue() {
		return DynamicConfigValue_Value_DEFAULT
	}
	return p.Value
}

var DynamicConfigValue_Filters_DEFAULT []*DynamicConfigFilter

func (p *DynamicConfigValue) GetFilters() []*DynamicConfigFilter {
	return p.Filters
}
func (p *DynamicConfigValue) IsSetValue() bool {
	return p.Value != nil
}

func (p *DynamicConfigValue) IsSetFilters() bool {
	return p.Filters != nil
}

func (p *DynamicConfigValue) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DynamicConfigValue) readField10(iprot thrift.TProtocol) error {
	p.Value = &shared.DataBlob{}
	if err := p.Value.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Value), err)
	}
	return nil
}

func (p *DynamicConfigValue) readField20(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*DynamicConfigFilter, 0, size)
	p.Filters = tSlice
	for i := 0; i < size; i++ {
		_elem2 := &DynamicConfigFilter{}
		if err := _elem2.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem2), err)
		}
		p.Filters = append(p.Filters, _elem2)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *DynamicConfigValue) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("DynamicConfigValue"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DynamicConfigValue) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetValue() {
		if err := oprot.WriteFieldBegin("value", thrift.STRUCT, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:value: ", p), err)
		}
		if err := p.Value.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Value), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:value: ", p), err)
		}
	}
	return err
}

func (p *DynamicConfigValue) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetFilters() {
		if err := oprot.WriteFieldBegin("filters", thrift.LIST, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:filters: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Filters)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Filters {
			if err := v.Write(oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:filters: ", p), err)
		}
	}
	return err
}

func (p *DynamicConfigValue) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DynamicConfigValue(%+v)", *p)
}

// Attributes:
//   - Name
//   - Value
type DynamicConfigFilter struct {
	// unused fields # 1 to 9
	Name *string `thrift:"name,10" json:"name,omitempty"`
	// unused fields # 11 to 19
	Value *shared.DataBlob `thrift:"value,20" json:"value,omitempty"`
}

func NewDynamicConfigFilter() *DynamicConfigFilter {
	return &DynamicConfigFilter{}
}

var DynamicConfigFilter_Name_DEFAULT string

func (p *DynamicConfigFilter) GetName() string {
	if !p.IsSetName() {
		return DynamicConfigFilter_Name_DEFAULT
	}
	return *p.Name
}

var DynamicConfigFilter_Value_DEFAULT *shared.DataBlob

func (p *DynamicConfigFilter) GetValue() *shared.DataBlob {
	if !p.IsSetValue() {
		return DynamicConfigFilter_Value_DEFAULT
	}
	return p.Value
}
func (p *DynamicConfigFilter) IsSetName() bool {
	return p.Name != nil
}

func (p *DynamicConfigFilter) IsSetValue() bool {
	return p.Value != nil
}

func (p *DynamicConfigFilter) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *DynamicConfigFilter) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.Name = &v
	}
	return nil
}

func (p *DynamicConfigFilter) readField20(iprot thrift.TProtocol) error {
	p.Value = &shared.DataBlob{}
	if err := p.Value.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Value), err)
	}
	return nil
}

func (p *DynamicConfigFilter) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("DynamicConfigFilter"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *DynamicConfigFilter) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetName() {
		if err := oprot.WriteFieldBegin("name", thrift.STRING, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:name: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Name)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.name (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:name: ", p), err)
		}
	}
	return err
}

func (p *DynamicConfigFilter) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetValue() {
		if err := oprot.WriteFieldBegin("value", thrift.STRUCT, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:value: ", p), err)
		}
		if err := p.Value.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Value), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:value: ", p), err)
		}
	}
	return err
}

func (p *DynamicConfigFilter) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DynamicConfigFilter(%+v)", *p)
}
