// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"cadence"
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  void RegisterDomain(RegisterDomainRequest registerRequest)")
	fmt.Fprintln(os.Stderr, "  DescribeDomainResponse DescribeDomain(DescribeDomainRequest describeRequest)")
	fmt.Fprintln(os.Stderr, "  ListDomainsResponse ListDomains(ListDomainsRequest listRequest)")
	fmt.Fprintln(os.Stderr, "  UpdateDomainResponse UpdateDomain(UpdateDomainRequest updateRequest)")
	fmt.Fprintln(os.Stderr, "  FailoverDomainResponse FailoverDomain(FailoverDomainRequest failoverRequest)")
	fmt.Fprintln(os.Stderr, "  void DeprecateDomain(DeprecateDomainRequest deprecateRequest)")
	fmt.Fprintln(os.Stderr, "  void DeleteDomain(DeleteDomainRequest deleteRequest)")
	fmt.Fprintln(os.Stderr, "  ListFailoverHistoryResponse ListFailoverHistory(ListFailoverHistoryRequest listRequest)")
	fmt.Fprintln(os.Stderr, "  RestartWorkflowExecutionResponse RestartWorkflowExecution(RestartWorkflowExecutionRequest restartRequest)")
	fmt.Fprintln(os.Stderr, "  DiagnoseWorkflowExecutionResponse DiagnoseWorkflowExecution(DiagnoseWorkflowExecutionRequest diagnoseRequest)")
	fmt.Fprintln(os.Stderr, "  StartWorkflowExecutionResponse StartWorkflowExecution(StartWorkflowExecutionRequest startRequest)")
	fmt.Fprintln(os.Stderr, "  StartWorkflowExecutionAsyncResponse StartWorkflowExecutionAsync(StartWorkflowExecutionAsyncRequest startRequest)")
	fmt.Fprintln(os.Stderr, "  GetWorkflowExecutionHistoryResponse GetWorkflowExecutionHistory(GetWorkflowExecutionHistoryRequest getRequest)")
	fmt.Fprintln(os.Stderr, "  PollForDecisionTaskResponse PollForDecisionTask(PollForDecisionTaskRequest pollRequest)")
	fmt.Fprintln(os.Stderr, "  RespondDecisionTaskCompletedResponse RespondDecisionTaskCompleted(RespondDecisionTaskCompletedRequest completeRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondDecisionTaskFailed(RespondDecisionTaskFailedRequest failedRequest)")
	fmt.Fprintln(os.Stderr, "  PollForActivityTaskResponse PollForActivityTask(PollForActivityTaskRequest pollRequest)")
	fmt.Fprintln(os.Stderr, "  RecordActivityTaskHeartbeatResponse RecordActivityTaskHeartbeat(RecordActivityTaskHeartbeatRequest heartbeatRequest)")
	fmt.Fprintln(os.Stderr, "  RecordActivityTaskHeartbeatResponse RecordActivityTaskHeartbeatByID(RecordActivityTaskHeartbeatByIDRequest heartbeatRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskCompleted(RespondActivityTaskCompletedRequest completeRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskCompletedByID(RespondActivityTaskCompletedByIDRequest completeRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskFailed(RespondActivityTaskFailedRequest failRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskFailedByID(RespondActivityTaskFailedByIDRequest failRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskCanceled(RespondActivityTaskCanceledRequest canceledRequest)")
	fmt.Fprintln(os.Stderr, "  void RespondActivityTaskCanceledByID(RespondActivityTaskCanceledByIDRequest canceledRequest)")
	fmt.Fprintln(os.Stderr, "  void RequestCancelWorkflowExecution(RequestCancelWorkflowExecutionRequest cancelRequest)")
	fmt.Fprintln(os.Stderr, "  void SignalWorkflowExecution(SignalWorkflowExecutionRequest signalRequest)")
	fmt.Fprintln(os.Stderr, "  StartWorkflowExecutionResponse SignalWithStartWorkflowExecution(SignalWithStartWorkflowExecutionRequest signalWithStartRequest)")
	fmt.Fprintln(os.Stderr, "  SignalWithStartWorkflowExecutionAsyncResponse SignalWithStartWorkflowExecutionAsync(SignalWithStartWorkflowExecutionAsyncRequest signalWithStartRequest)")
	fmt.Fprintln(os.Stderr, "  ResetWorkflowExecutionResponse ResetWorkflowExecution(ResetWorkflowExecutionRequest resetRequest)")
	fmt.Fprintln(os.Stderr, "  void TerminateWorkflowExecution(TerminateWorkflowExecutionRequest terminateRequest)")
	fmt.Fprintln(os.Stderr, "  ListOpenWorkflowExecutionsResponse ListOpenWorkflowExecutions(ListOpenWorkflowExecutionsRequest listRequest)")
	fmt.Fprintln(os.Stderr, "  ListClosedWorkflowExecutionsResponse ListClosedWorkflowExecutions(ListClosedWorkflowExecutionsRequest listRequest)")
	fmt.Fprintln(os.Stderr, "  ListWorkflowExecutionsResponse ListWorkflowExecutions(ListWorkflowExecutionsRequest listRequest)")
	fmt.Fprintln(os.Stderr, "  ListArchivedWorkflowExecutionsResponse ListArchivedWorkflowExecutions(ListArchivedWorkflowExecutionsRequest listRequest)")
	fmt.Fprintln(os.Stderr, "  ListWorkflowExecutionsResponse ScanWorkflowExecutions(ListWorkflowExecutionsRequest listRequest)")
	fmt.Fprintln(os.Stderr, "  CountWorkflowExecutionsResponse CountWorkflowExecutions(CountWorkflowExecutionsRequest countRequest)")
	fmt.Fprintln(os.Stderr, "  GetSearchAttributesResponse GetSearchAttributes()")
	fmt.Fprintln(os.Stderr, "  void RespondQueryTaskCompleted(RespondQueryTaskCompletedRequest completeRequest)")
	fmt.Fprintln(os.Stderr, "  ResetStickyTaskListResponse ResetStickyTaskList(ResetStickyTaskListRequest resetRequest)")
	fmt.Fprintln(os.Stderr, "  QueryWorkflowResponse QueryWorkflow(QueryWorkflowRequest queryRequest)")
	fmt.Fprintln(os.Stderr, "  DescribeWorkflowExecutionResponse DescribeWorkflowExecution(DescribeWorkflowExecutionRequest describeRequest)")
	fmt.Fprintln(os.Stderr, "  DescribeTaskListResponse DescribeTaskList(DescribeTaskListRequest request)")
	fmt.Fprintln(os.Stderr, "  ClusterInfo GetClusterInfo()")
	fmt.Fprintln(os.Stderr, "  GetTaskListsByDomainResponse GetTaskListsByDomain(GetTaskListsByDomainRequest request)")
	fmt.Fprintln(os.Stderr, "  ListTaskListPartitionsResponse ListTaskListPartitions(ListTaskListPartitionsRequest request)")
	fmt.Fprintln(os.Stderr, "  void RefreshWorkflowTasks(RefreshWorkflowTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  CreateScheduleResponse CreateSchedule(CreateScheduleRequest request)")
	fmt.Fprintln(os.Stderr, "  DescribeScheduleResponse DescribeSchedule(DescribeScheduleRequest request)")
	fmt.Fprintln(os.Stderr, "  UpdateScheduleResponse UpdateSchedule(UpdateScheduleRequest request)")
	fmt.Fprintln(os.Stderr, "  DeleteScheduleResponse DeleteSchedule(DeleteScheduleRequest request)")
	fmt.Fprintln(os.Stderr, "  PauseScheduleResponse PauseSchedule(PauseScheduleRequest request)")
	fmt.Fprintln(os.Stderr, "  UnpauseScheduleResponse UnpauseSchedule(UnpauseScheduleRequest request)")
	fmt.Fprintln(os.Stderr, "  BackfillScheduleResponse BackfillSchedule(BackfillScheduleRequest request)")
	fmt.Fprintln(os.Stderr, "  ListSchedulesResponse ListSchedules(ListSchedulesRequest request)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := cadence.NewWorkflowServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "RegisterDomain":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RegisterDomain requires 1 args")
			flag.Usage()
		}
		arg112 := flag.Arg(1)
		mbTrans113 := thrift.NewTMemoryBufferLen(len(arg112))
		defer mbTrans113.Close()
		_, err114 := mbTrans113.WriteString(arg112)
		if err114 != nil {
			Usage()
			return
		}
		factory115 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt116 := factory115.GetProtocol(mbTrans113)
		argvalue0 := cadence.NewRegisterDomainRequest()
		err117 := argvalue0.Read(jsProt116)
		if err117 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RegisterDomain(value0))
		fmt.Print("\n")
		break
	case "DescribeDomain":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeDomain requires 1 args")
			flag.Usage()
		}
		arg118 := flag.Arg(1)
		mbTrans119 := thrift.NewTMemoryBufferLen(len(arg118))
		defer mbTrans119.Close()
		_, err120 := mbTrans119.WriteString(arg118)
		if err120 != nil {
			Usage()
			return
		}
		factory121 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt122 := factory121.GetProtocol(mbTrans119)
		argvalue0 := cadence.NewDescribeDomainRequest()
		err123 := argvalue0.Read(jsProt122)
		if err123 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeDomain(value0))
		fmt.Print("\n")
		break
	case "ListDomains":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListDomains requires 1 args")
			flag.Usage()
		}
		arg124 := flag.Arg(1)
		mbTrans125 := thrift.NewTMemoryBufferLen(len(arg124))
		defer mbTrans125.Close()
		_, err126 := mbTrans125.WriteString(arg124)
		if err126 != nil {
			Usage()
			return
		}
		factory127 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt128 := factory127.GetProtocol(mbTrans125)
		argvalue0 := cadence.NewListDomainsRequest()
		err129 := argvalue0.Read(jsProt128)
		if err129 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListDomains(value0))
		fmt.Print("\n")
		break
	case "UpdateDomain":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateDomain requires 1 args")
			flag.Usage()
		}
		arg130 := flag.Arg(1)
		mbTrans131 := thrift.NewTMemoryBufferLen(len(arg130))
		defer mbTrans131.Close()
		_, err132 := mbTrans131.WriteString(arg130)
		if err132 != nil {
			Usage()
			return
		}
		factory133 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt134 := factory133.GetProtocol(mbTrans131)
		argvalue0 := cadence.NewUpdateDomainRequest()
		err135 := argvalue0.Read(jsProt134)
		if err135 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateDomain(value0))
		fmt.Print("\n")
		break
	case "FailoverDomain":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "FailoverDomain requires 1 args")
			flag.Usage()
		}
		arg136 := flag.Arg(1)
		mbTrans137 := thrift.NewTMemoryBufferLen(len(arg136))
		defer mbTrans137.Close()
		_, err138 := mbTrans137.WriteString(arg136)
		if err138 != nil {
			Usage()
			return
		}
		factory139 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt140 := factory139.GetProtocol(mbTrans137)
		argvalue0 := cadence.NewFailoverDomainRequest()
		err141 := argvalue0.Read(jsProt140)
		if err141 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.FailoverDomain(value0))
		fmt.Print("\n")
		break
	case "DeprecateDomain":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeprecateDomain requires 1 args")
			flag.Usage()
		}
		arg142 := flag.Arg(1)
		mbTrans143 := thrift.NewTMemoryBufferLen(len(arg142))
		defer mbTrans143.Close()
		_, err144 := mbTrans143.WriteString(arg142)
		if err144 != nil {
			Usage()
			return
		}
		factory145 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt146 := factory145.GetProtocol(mbTrans143)
		argvalue0 := cadence.NewDeprecateDomainRequest()
		err147 := argvalue0.Read(jsProt146)
		if err147 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeprecateDomain(value0))
		fmt.Print("\n")
		break
	case "DeleteDomain":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteDomain requires 1 args")
			flag.Usage()
		}
		arg148 := flag.Arg(1)
		mbTrans149 := thrift.NewTMemoryBufferLen(len(arg148))
		defer mbTrans149.Close()
		_, err150 := mbTrans149.WriteString(arg148)
		if err150 != nil {
			Usage()
			return
		}
		factory151 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt152 := factory151.GetProtocol(mbTrans149)
		argvalue0 := cadence.NewDeleteDomainRequest()
		err153 := argvalue0.Read(jsProt152)
		if err153 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteDomain(value0))
		fmt.Print("\n")
		break
	case "ListFailoverHistory":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListFailoverHistory requires 1 args")
			flag.Usage()
		}
		arg154 := flag.Arg(1)
		mbTrans155 := thrift.NewTMemoryBufferLen(len(arg154))
		defer mbTrans155.Close()
		_, err156 := mbTrans155.WriteString(arg154)
		if err156 != nil {
			Usage()
			return
		}
		factory157 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt158 := factory157.GetProtocol(mbTrans155)
		argvalue0 := cadence.NewListFailoverHistoryRequest()
		err159 := argvalue0.Read(jsProt158)
		if err159 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListFailoverHistory(value0))
		fmt.Print("\n")
		break
	case "RestartWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RestartWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg160 := flag.Arg(1)
		mbTrans161 := thrift.NewTMemoryBufferLen(len(arg160))
		defer mbTrans161.Close()
		_, err162 := mbTrans161.WriteString(arg160)
		if err162 != nil {
			Usage()
			return
		}
		factory163 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt164 := factory163.GetProtocol(mbTrans161)
		argvalue0 := cadence.NewRestartWorkflowExecutionRequest()
		err165 := argvalue0.Read(jsProt164)
		if err165 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RestartWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "DiagnoseWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DiagnoseWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg166 := flag.Arg(1)
		mbTrans167 := thrift.NewTMemoryBufferLen(len(arg166))
		defer mbTrans167.Close()
		_, err168 := mbTrans167.WriteString(arg166)
		if err168 != nil {
			Usage()
			return
		}
		factory169 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt170 := factory169.GetProtocol(mbTrans167)
		argvalue0 := cadence.NewDiagnoseWorkflowExecutionRequest()
		err171 := argvalue0.Read(jsProt170)
		if err171 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DiagnoseWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "StartWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "StartWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg172 := flag.Arg(1)
		mbTrans173 := thrift.NewTMemoryBufferLen(len(arg172))
		defer mbTrans173.Close()
		_, err174 := mbTrans173.WriteString(arg172)
		if err174 != nil {
			Usage()
			return
		}
		factory175 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt176 := factory175.GetProtocol(mbTrans173)
		argvalue0 := cadence.NewStartWorkflowExecutionRequest()
		err177 := argvalue0.Read(jsProt176)
		if err177 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.StartWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "StartWorkflowExecutionAsync":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "StartWorkflowExecutionAsync requires 1 args")
			flag.Usage()
		}
		arg178 := flag.Arg(1)
		mbTrans179 := thrift.NewTMemoryBufferLen(len(arg178))
		defer mbTrans179.Close()
		_, err180 := mbTrans179.WriteString(arg178)
		if err180 != nil {
			Usage()
			return
		}
		factory181 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt182 := factory181.GetProtocol(mbTrans179)
		argvalue0 := cadence.NewStartWorkflowExecutionAsyncRequest()
		err183 := argvalue0.Read(jsProt182)
		if err183 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.StartWorkflowExecutionAsync(value0))
		fmt.Print("\n")
		break
	case "GetWorkflowExecutionHistory":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetWorkflowExecutionHistory requires 1 args")
			flag.Usage()
		}
		arg184 := flag.Arg(1)
		mbTrans185 := thrift.NewTMemoryBufferLen(len(arg184))
		defer mbTrans185.Close()
		_, err186 := mbTrans185.WriteString(arg184)
		if err186 != nil {
			Usage()
			return
		}
		factory187 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt188 := factory187.GetProtocol(mbTrans185)
		argvalue0 := cadence.NewGetWorkflowExecutionHistoryRequest()
		err189 := argvalue0.Read(jsProt188)
		if err189 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetWorkflowExecutionHistory(value0))
		fmt.Print("\n")
		break
	case "PollForDecisionTask":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "PollForDecisionTask requires 1 args")
			flag.Usage()
		}
		arg190 := flag.Arg(1)
		mbTrans191 := thrift.NewTMemoryBufferLen(len(arg190))
		defer mbTrans191.Close()
		_, err192 := mbTrans191.WriteString(arg190)
		if err192 != nil {
			Usage()
			return
		}
		factory193 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt194 := factory193.GetProtocol(mbTrans191)
		argvalue0 := cadence.NewPollForDecisionTaskRequest()
		err195 := argvalue0.Read(jsProt194)
		if err195 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.PollForDecisionTask(value0))
		fmt.Print("\n")
		break
	case "RespondDecisionTaskCompleted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondDecisionTaskCompleted requires 1 args")
			flag.Usage()
		}
		arg196 := flag.Arg(1)
		mbTrans197 := thrift.NewTMemoryBufferLen(len(arg196))
		defer mbTrans197.Close()
		_, err198 := mbTrans197.WriteString(arg196)
		if err198 != nil {
			Usage()
			return
		}
		factory199 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt200 := factory199.GetProtocol(mbTrans197)
		argvalue0 := cadence.NewRespondDecisionTaskCompletedRequest()
		err201 := argvalue0.Read(jsProt200)
		if err201 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondDecisionTaskCompleted(value0))
		fmt.Print("\n")
		break
	case "RespondDecisionTaskFailed":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondDecisionTaskFailed requires 1 args")
			flag.Usage()
		}
		arg202 := flag.Arg(1)
		mbTrans203 := thrift.NewTMemoryBufferLen(len(arg202))
		defer mbTrans203.Close()
		_, err204 := mbTrans203.WriteString(arg202)
		if err204 != nil {
			Usage()
			return
		}
		factory205 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt206 := factory205.GetProtocol(mbTrans203)
		argvalue0 := cadence.NewRespondDecisionTaskFailedRequest()
		err207 := argvalue0.Read(jsProt206)
		if err207 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondDecisionTaskFailed(value0))
		fmt.Print("\n")
		break
	case "PollForActivityTask":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "PollForActivityTask requires 1 args")
			flag.Usage()
		}
		arg208 := flag.Arg(1)
		mbTrans209 := thrift.NewTMemoryBufferLen(len(arg208))
		defer mbTrans209.Close()
		_, err210 := mbTrans209.WriteString(arg208)
		if err210 != nil {
			Usage()
			return
		}
		factory211 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt212 := factory211.GetProtocol(mbTrans209)
		argvalue0 := cadence.NewPollForActivityTaskRequest()
		err213 := argvalue0.Read(jsProt212)
		if err213 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.PollForActivityTask(value0))
		fmt.Print("\n")
		break
	case "RecordActivityTaskHeartbeat":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RecordActivityTaskHeartbeat requires 1 args")
			flag.Usage()
		}
		arg214 := flag.Arg(1)
		mbTrans215 := thrift.NewTMemoryBufferLen(len(arg214))
		defer mbTrans215.Close()
		_, err216 := mbTrans215.WriteString(arg214)
		if err216 != nil {
			Usage()
			return
		}
		factory217 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt218 := factory217.GetProtocol(mbTrans215)
		argvalue0 := cadence.NewRecordActivityTaskHeartbeatRequest()
		err219 := argvalue0.Read(jsProt218)
		if err219 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RecordActivityTaskHeartbeat(value0))
		fmt.Print("\n")
		break
	case "RecordActivityTaskHeartbeatByID":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RecordActivityTaskHeartbeatByID requires 1 args")
			flag.Usage()
		}
		arg220 := flag.Arg(1)
		mbTrans221 := thrift.NewTMemoryBufferLen(len(arg220))
		defer mbTrans221.Close()
		_, err222 := mbTrans221.WriteString(arg220)
		if err222 != nil {
			Usage()
			return
		}
		factory223 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt224 := factory223.GetProtocol(mbTrans221)
		argvalue0 := cadence.NewRecordActivityTaskHeartbeatByIDRequest()
		err225 := argvalue0.Read(jsProt224)
		if err225 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RecordActivityTaskHeartbeatByID(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskCompleted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskCompleted requires 1 args")
			flag.Usage()
		}
		arg226 := flag.Arg(1)
		mbTrans227 := thrift.NewTMemoryBufferLen(len(arg226))
		defer mbTrans227.Close()
		_, err228 := mbTrans227.WriteString(arg226)
		if err228 != nil {
			Usage()
			return
		}
		factory229 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt230 := factory229.GetProtocol(mbTrans227)
		argvalue0 := cadence.NewRespondActivityTaskCompletedRequest()
		err231 := argvalue0.Read(jsProt230)
		if err231 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskCompleted(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskCompletedByID":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskCompletedByID requires 1 args")
			flag.Usage()
		}
		arg232 := flag.Arg(1)
		mbTrans233 := thrift.NewTMemoryBufferLen(len(arg232))
		defer mbTrans233.Close()
		_, err234 := mbTrans233.WriteString(arg232)
		if err234 != nil {
			Usage()
			return
		}
		factory235 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt236 := factory235.GetProtocol(mbTrans233)
		argvalue0 := cadence.NewRespondActivityTaskCompletedByIDRequest()
		err237 := argvalue0.Read(jsProt236)
		if err237 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskCompletedByID(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskFailed":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskFailed requires 1 args")
			flag.Usage()
		}
		arg238 := flag.Arg(1)
		mbTrans239 := thrift.NewTMemoryBufferLen(len(arg238))
		defer mbTrans239.Close()
		_, err240 := mbTrans239.WriteString(arg238)
		if err240 != nil {
			Usage()
			return
		}
		factory241 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt242 := factory241.GetProtocol(mbTrans239)
		argvalue0 := cadence.NewRespondActivityTaskFailedRequest()
		err243 := argvalue0.Read(jsProt242)
		if err243 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskFailed(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskFailedByID":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskFailedByID requires 1 args")
			flag.Usage()
		}
		arg244 := flag.Arg(1)
		mbTrans245 := thrift.NewTMemoryBufferLen(len(arg244))
		defer mbTrans245.Close()
		_, err246 := mbTrans245.WriteString(arg244)
		if err246 != nil {
			Usage()
			return
		}
		factory247 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt248 := factory247.GetProtocol(mbTrans245)
		argvalue0 := cadence.NewRespondActivityTaskFailedByIDRequest()
		err249 := argvalue0.Read(jsProt248)
		if err249 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskFailedByID(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskCanceled":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskCanceled requires 1 args")
			flag.Usage()
		}
		arg250 := flag.Arg(1)
		mbTrans251 := thrift.NewTMemoryBufferLen(len(arg250))
		defer mbTrans251.Close()
		_, err252 := mbTrans251.WriteString(arg250)
		if err252 != nil {
			Usage()
			return
		}
		factory253 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt254 := factory253.GetProtocol(mbTrans251)
		argvalue0 := cadence.NewRespondActivityTaskCanceledRequest()
		err255 := argvalue0.Read(jsProt254)
		if err255 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskCanceled(value0))
		fmt.Print("\n")
		break
	case "RespondActivityTaskCanceledByID":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondActivityTaskCanceledByID requires 1 args")
			flag.Usage()
		}
		arg256 := flag.Arg(1)
		mbTrans257 := thrift.NewTMemoryBufferLen(len(arg256))
		defer mbTrans257.Close()
		_, err258 := mbTrans257.WriteString(arg256)
		if err258 != nil {
			Usage()
			return
		}
		factory259 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt260 := factory259.GetProtocol(mbTrans257)
		argvalue0 := cadence.NewRespondActivityTaskCanceledByIDRequest()
		err261 := argvalue0.Read(jsProt260)
		if err261 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondActivityTaskCanceledByID(value0))
		fmt.Print("\n")
		break
	case "RequestCancelWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RequestCancelWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg262 := flag.Arg(1)
		mbTrans263 := thrift.NewTMemoryBufferLen(len(arg262))
		defer mbTrans263.Close()
		_, err264 := mbTrans263.WriteString(arg262)
		if err264 != nil {
			Usage()
			return
		}
		factory265 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt266 := factory265.GetProtocol(mbTrans263)
		argvalue0 := cadence.NewRequestCancelWorkflowExecutionRequest()
		err267 := argvalue0.Read(jsProt266)
		if err267 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RequestCancelWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "SignalWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SignalWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg268 := flag.Arg(1)
		mbTrans269 := thrift.NewTMemoryBufferLen(len(arg268))
		defer mbTrans269.Close()
		_, err270 := mbTrans269.WriteString(arg268)
		if err270 != nil {
			Usage()
			return
		}
		factory271 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt272 := factory271.GetProtocol(mbTrans269)
		argvalue0 := cadence.NewSignalWorkflowExecutionRequest()
		err273 := argvalue0.Read(jsProt272)
		if err273 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SignalWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "SignalWithStartWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SignalWithStartWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg274 := flag.Arg(1)
		mbTrans275 := thrift.NewTMemoryBufferLen(len(arg274))
		defer mbTrans275.Close()
		_, err276 := mbTrans275.WriteString(arg274)
		if err276 != nil {
			Usage()
			return
		}
		factory277 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt278 := factory277.GetProtocol(mbTrans275)
		argvalue0 := cadence.NewSignalWithStartWorkflowExecutionRequest()
		err279 := argvalue0.Read(jsProt278)
		if err279 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SignalWithStartWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "SignalWithStartWorkflowExecutionAsync":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SignalWithStartWorkflowExecutionAsync requires 1 args")
			flag.Usage()
		}
		arg280 := flag.Arg(1)
		mbTrans281 := thrift.NewTMemoryBufferLen(len(arg280))
		defer mbTrans281.Close()
		_, err282 := mbTrans281.WriteString(arg280)
		if err282 != nil {
			Usage()
			return
		}
		factory283 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt284 := factory283.GetProtocol(mbTrans281)
		argvalue0 := cadence.NewSignalWithStartWorkflowExecutionAsyncRequest()
		err285 := argvalue0.Read(jsProt284)
		if err285 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SignalWithStartWorkflowExecutionAsync(value0))
		fmt.Print("\n")
		break
	case "ResetWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ResetWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg286 := flag.Arg(1)
		mbTrans287 := thrift.NewTMemoryBufferLen(len(arg286))
		defer mbTrans287.Close()
		_, err288 := mbTrans287.WriteString(arg286)
		if err288 != nil {
			Usage()
			return
		}
		factory289 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt290 := factory289.GetProtocol(mbTrans287)
		argvalue0 := cadence.NewResetWorkflowExecutionRequest()
		err291 := argvalue0.Read(jsProt290)
		if err291 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ResetWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "TerminateWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "TerminateWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg292 := flag.Arg(1)
		mbTrans293 := thrift.NewTMemoryBufferLen(len(arg292))
		defer mbTrans293.Close()
		_, err294 := mbTrans293.WriteString(arg292)
		if err294 != nil {
			Usage()
			return
		}
		factory295 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt296 := factory295.GetProtocol(mbTrans293)
		argvalue0 := cadence.NewTerminateWorkflowExecutionRequest()
		err297 := argvalue0.Read(jsProt296)
		if err297 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.TerminateWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "ListOpenWorkflowExecutions":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListOpenWorkflowExecutions requires 1 args")
			flag.Usage()
		}
		arg298 := flag.Arg(1)
		mbTrans299 := thrift.NewTMemoryBufferLen(len(arg298))
		defer mbTrans299.Close()
		_, err300 := mbTrans299.WriteString(arg298)
		if err300 != nil {
			Usage()
			return
		}
		factory301 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt302 := factory301.GetProtocol(mbTrans299)
		argvalue0 := cadence.NewListOpenWorkflowExecutionsRequest()
		err303 := argvalue0.Read(jsProt302)
		if err303 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListOpenWorkflowExecutions(value0))
		fmt.Print("\n")
		break
	case "ListClosedWorkflowExecutions":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListClosedWorkflowExecutions requires 1 args")
			flag.Usage()
		}
		arg304 := flag.Arg(1)
		mbTrans305 := thrift.NewTMemoryBufferLen(len(arg304))
		defer mbTrans305.Close()
		_, err306 := mbTrans305.WriteString(arg304)
		if err306 != nil {
			Usage()
			return
		}
		factory307 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt308 := factory307.GetProtocol(mbTrans305)
		argvalue0 := cadence.NewListClosedWorkflowExecutionsRequest()
		err309 := argvalue0.Read(jsProt308)
		if err309 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListClosedWorkflowExecutions(value0))
		fmt.Print("\n")
		break
	case "ListWorkflowExecutions":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListWorkflowExecutions requires 1 args")
			flag.Usage()
		}
		arg310 := flag.Arg(1)
		mbTrans311 := thrift.NewTMemoryBufferLen(len(arg310))
		defer mbTrans311.Close()
		_, err312 := mbTrans311.WriteString(arg310)
		if err312 != nil {
			Usage()
			return
		}
		factory313 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt314 := factory313.GetProtocol(mbTrans311)
		argvalue0 := cadence.NewListWorkflowExecutionsRequest()
		err315 := argvalue0.Read(jsProt314)
		if err315 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListWorkflowExecutions(value0))
		fmt.Print("\n")
		break
	case "ListArchivedWorkflowExecutions":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListArchivedWorkflowExecutions requires 1 args")
			flag.Usage()
		}
		arg316 := flag.Arg(1)
		mbTrans317 := thrift.NewTMemoryBufferLen(len(arg316))
		defer mbTrans317.Close()
		_, err318 := mbTrans317.WriteString(arg316)
		if err318 != nil {
			Usage()
			return
		}
		factory319 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt320 := factory319.GetProtocol(mbTrans317)
		argvalue0 := cadence.NewListArchivedWorkflowExecutionsRequest()
		err321 := argvalue0.Read(jsProt320)
		if err321 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListArchivedWorkflowExecutions(value0))
		fmt.Print("\n")
		break
	case "ScanWorkflowExecutions":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ScanWorkflowExecutions requires 1 args")
			flag.Usage()
		}
		arg322 := flag.Arg(1)
		mbTrans323 := thrift.NewTMemoryBufferLen(len(arg322))
		defer mbTrans323.Close()
		_, err324 := mbTrans323.WriteString(arg322)
		if err324 != nil {
			Usage()
			return
		}
		factory325 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt326 := factory325.GetProtocol(mbTrans323)
		argvalue0 := cadence.NewListWorkflowExecutionsRequest()
		err327 := argvalue0.Read(jsProt326)
		if err327 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ScanWorkflowExecutions(value0))
		fmt.Print("\n")
		break
	case "CountWorkflowExecutions":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CountWorkflowExecutions requires 1 args")
			flag.Usage()
		}
		arg328 := flag.Arg(1)
		mbTrans329 := thrift.NewTMemoryBufferLen(len(arg328))
		defer mbTrans329.Close()
		_, err330 := mbTrans329.WriteString(arg328)
		if err330 != nil {
			Usage()
			return
		}
		factory331 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt332 := factory331.GetProtocol(mbTrans329)
		argvalue0 := cadence.NewCountWorkflowExecutionsRequest()
		err333 := argvalue0.Read(jsProt332)
		if err333 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountWorkflowExecutions(value0))
		fmt.Print("\n")
		break
	case "GetSearchAttributes":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetSearchAttributes requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetSearchAttributes())
		fmt.Print("\n")
		break
	case "RespondQueryTaskCompleted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondQueryTaskCompleted requires 1 args")
			flag.Usage()
		}
		arg334 := flag.Arg(1)
		mbTrans335 := thrift.NewTMemoryBufferLen(len(arg334))
		defer mbTrans335.Close()
		_, err336 := mbTrans335.WriteString(arg334)
		if err336 != nil {
			Usage()
			return
		}
		factory337 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt338 := factory337.GetProtocol(mbTrans335)
		argvalue0 := cadence.NewRespondQueryTaskCompletedRequest()
		err339 := argvalue0.Read(jsProt338)
		if err339 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondQueryTaskCompleted(value0))
		fmt.Print("\n")
		break
	case "ResetStickyTaskList":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ResetStickyTaskList requires 1 args")
			flag.Usage()
		}
		arg340 := flag.Arg(1)
		mbTrans341 := thrift.NewTMemoryBufferLen(len(arg340))
		defer mbTrans341.Close()
		_, err342 := mbTrans341.WriteString(arg340)
		if err342 != nil {
			Usage()
			return
		}
		factory343 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt344 := factory343.GetProtocol(mbTrans341)
		argvalue0 := cadence.NewResetStickyTaskListRequest()
		err345 := argvalue0.Read(jsProt344)
		if err345 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ResetStickyTaskList(value0))
		fmt.Print("\n")
		break
	case "QueryWorkflow":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryWorkflow requires 1 args")
			flag.Usage()
		}
		arg346 := flag.Arg(1)
		mbTrans347 := thrift.NewTMemoryBufferLen(len(arg346))
		defer mbTrans347.Close()
		_, err348 := mbTrans347.WriteString(arg346)
		if err348 != nil {
			Usage()
			return
		}
		factory349 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt350 := factory349.GetProtocol(mbTrans347)
		argvalue0 := cadence.NewQueryWorkflowRequest()
		err351 := argvalue0.Read(jsProt350)
		if err351 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryWorkflow(value0))
		fmt.Print("\n")
		break
	case "DescribeWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg352 := flag.Arg(1)
		mbTrans353 := thrift.NewTMemoryBufferLen(len(arg352))
		defer mbTrans353.Close()
		_, err354 := mbTrans353.WriteString(arg352)
		if err354 != nil {
			Usage()
			return
		}
		factory355 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt356 := factory355.GetProtocol(mbTrans353)
		argvalue0 := cadence.NewDescribeWorkflowExecutionRequest()
		err357 := argvalue0.Read(jsProt356)
		if err357 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "DescribeTaskList":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeTaskList requires 1 args")
			flag.Usage()
		}
		arg358 := flag.Arg(1)
		mbTrans359 := thrift.NewTMemoryBufferLen(len(arg358))
		defer mbTrans359.Close()
		_, err360 := mbTrans359.WriteString(arg358)
		if err360 != nil {
			Usage()
			return
		}
		factory361 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt362 := factory361.GetProtocol(mbTrans359)
		argvalue0 := cadence.NewDescribeTaskListRequest()
		err363 := argvalue0.Read(jsProt362)
		if err363 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeTaskList(value0))
		fmt.Print("\n")
		break
	case "GetClusterInfo":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetClusterInfo requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetClusterInfo())
		fmt.Print("\n")
		break
	case "GetTaskListsByDomain":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTaskListsByDomain requires 1 args")
			flag.Usage()
		}
		arg364 := flag.Arg(1)
		mbTrans365 := thrift.NewTMemoryBufferLen(len(arg364))
		defer mbTrans365.Close()
		_, err366 := mbTrans365.WriteString(arg364)
		if err366 != nil {
			Usage()
			return
		}
		factory367 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt368 := factory367.GetProtocol(mbTrans365)
		argvalue0 := cadence.NewGetTaskListsByDomainRequest()
		err369 := argvalue0.Read(jsProt368)
		if err369 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetTaskListsByDomain(value0))
		fmt.Print("\n")
		break
	case "ListTaskListPartitions":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListTaskListPartitions requires 1 args")
			flag.Usage()
		}
		arg370 := flag.Arg(1)
		mbTrans371 := thrift.NewTMemoryBufferLen(len(arg370))
		defer mbTrans371.Close()
		_, err372 := mbTrans371.WriteString(arg370)
		if err372 != nil {
			Usage()
			return
		}
		factory373 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt374 := factory373.GetProtocol(mbTrans371)
		argvalue0 := cadence.NewListTaskListPartitionsRequest()
		err375 := argvalue0.Read(jsProt374)
		if err375 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListTaskListPartitions(value0))
		fmt.Print("\n")
		break
	case "RefreshWorkflowTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RefreshWorkflowTasks requires 1 args")
			flag.Usage()
		}
		arg376 := flag.Arg(1)
		mbTrans377 := thrift.NewTMemoryBufferLen(len(arg376))
		defer mbTrans377.Close()
		_, err378 := mbTrans377.WriteString(arg376)
		if err378 != nil {
			Usage()
			return
		}
		factory379 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt380 := factory379.GetProtocol(mbTrans377)
		argvalue0 := cadence.NewRefreshWorkflowTasksRequest()
		err381 := argvalue0.Read(jsProt380)
		if err381 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RefreshWorkflowTasks(value0))
		fmt.Print("\n")
		break
	case "CreateSchedule":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateSchedule requires 1 args")
			flag.Usage()
		}
		arg382 := flag.Arg(1)
		mbTrans383 := thrift.NewTMemoryBufferLen(len(arg382))
		defer mbTrans383.Close()
		_, err384 := mbTrans383.WriteString(arg382)
		if err384 != nil {
			Usage()
			return
		}
		factory385 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt386 := factory385.GetProtocol(mbTrans383)
		argvalue0 := cadence.NewCreateScheduleRequest()
		err387 := argvalue0.Read(jsProt386)
		if err387 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateSchedule(value0))
		fmt.Print("\n")
		break
	case "DescribeSchedule":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeSchedule requires 1 args")
			flag.Usage()
		}
		arg388 := flag.Arg(1)
		mbTrans389 := thrift.NewTMemoryBufferLen(len(arg388))
		defer mbTrans389.Close()
		_, err390 := mbTrans389.WriteString(arg388)
		if err390 != nil {
			Usage()
			return
		}
		factory391 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt392 := factory391.GetProtocol(mbTrans389)
		argvalue0 := cadence.NewDescribeScheduleRequest()
		err393 := argvalue0.Read(jsProt392)
		if err393 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeSchedule(value0))
		fmt.Print("\n")
		break
	case "UpdateSchedule":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateSchedule requires 1 args")
			flag.Usage()
		}
		arg394 := flag.Arg(1)
		mbTrans395 := thrift.NewTMemoryBufferLen(len(arg394))
		defer mbTrans395.Close()
		_, err396 := mbTrans395.WriteString(arg394)
		if err396 != nil {
			Usage()
			return
		}
		factory397 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt398 := factory397.GetProtocol(mbTrans395)
		argvalue0 := cadence.NewUpdateScheduleRequest()
		err399 := argvalue0.Read(jsProt398)
		if err399 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateSchedule(value0))
		fmt.Print("\n")
		break
	case "DeleteSchedule":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteSchedule requires 1 args")
			flag.Usage()
		}
		arg400 := flag.Arg(1)
		mbTrans401 := thrift.NewTMemoryBufferLen(len(arg400))
		defer mbTrans401.Close()
		_, err402 := mbTrans401.WriteString(arg400)
		if err402 != nil {
			Usage()
			return
		}
		factory403 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt404 := factory403.GetProtocol(mbTrans401)
		argvalue0 := cadence.NewDeleteScheduleRequest()
		err405 := argvalue0.Read(jsProt404)
		if err405 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteSchedule(value0))
		fmt.Print("\n")
		break
	case "PauseSchedule":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "PauseSchedule requires 1 args")
			flag.Usage()
		}
		arg406 := flag.Arg(1)
		mbTrans407 := thrift.NewTMemoryBufferLen(len(arg406))
		defer mbTrans407.Close()
		_, err408 := mbTrans407.WriteString(arg406)
		if err408 != nil {
			Usage()
			return
		}
		factory409 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt410 := factory409.GetProtocol(mbTrans407)
		argvalue0 := cadence.NewPauseScheduleRequest()
		err411 := argvalue0.Read(jsProt410)
		if err411 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.PauseSchedule(value0))
		fmt.Print("\n")
		break
	case "UnpauseSchedule":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UnpauseSchedule requires 1 args")
			flag.Usage()
		}
		arg412 := flag.Arg(1)
		mbTrans413 := thrift.NewTMemoryBufferLen(len(arg412))
		defer mbTrans413.Close()
		_, err414 := mbTrans413.WriteString(arg412)
		if err414 != nil {
			Usage()
			return
		}
		factory415 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt416 := factory415.GetProtocol(mbTrans413)
		argvalue0 := cadence.NewUnpauseScheduleRequest()
		err417 := argvalue0.Read(jsProt416)
		if err417 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UnpauseSchedule(value0))
		fmt.Print("\n")
		break
	case "BackfillSchedule":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "BackfillSchedule requires 1 args")
			flag.Usage()
		}
		arg418 := flag.Arg(1)
		mbTrans419 := thrift.NewTMemoryBufferLen(len(arg418))
		defer mbTrans419.Close()
		_, err420 := mbTrans419.WriteString(arg418)
		if err420 != nil {
			Usage()
			return
		}
		factory421 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt422 := factory421.GetProtocol(mbTrans419)
		argvalue0 := cadence.NewBackfillScheduleRequest()
		err423 := argvalue0.Read(jsProt422)
		if err423 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.BackfillSchedule(value0))
		fmt.Print("\n")
		break
	case "ListSchedules":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListSchedules requires 1 args")
			flag.Usage()
		}
		arg424 := flag.Arg(1)
		mbTrans425 := thrift.NewTMemoryBufferLen(len(arg424))
		defer mbTrans425.Close()
		_, err426 := mbTrans425.WriteString(arg424)
		if err426 != nil {
			Usage()
			return
		}
		factory427 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt428 := factory427.GetProtocol(mbTrans425)
		argvalue0 := cadence.NewListSchedulesRequest()
		err429 := argvalue0.Read(jsProt428)
		if err429 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ListSchedules(value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
