// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package indexer

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"shared"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__
var GoUnusedProtection__ int

type MessageType int64

const (
	MessageType_Index  MessageType = 0
	MessageType_Delete MessageType = 1
	MessageType_Create MessageType = 2
)

func (p MessageType) String() string {
	switch p {
	case MessageType_Index:
		return "Index"
	case MessageType_Delete:
		return "Delete"
	case MessageType_Create:
		return "Create"
	}
	return "<UNSET>"
}

func MessageTypeFromString(s string) (MessageType, error) {
	switch s {
	case "Index":
		return MessageType_Index, nil
	case "Delete":
		return MessageType_Delete, nil
	case "Create":
		return MessageType_Create, nil
	}
	return MessageType(0), fmt.Errorf("not a valid MessageType string")
}

func MessageTypePtr(v MessageType) *MessageType { return &v }

func (p MessageType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *MessageType) UnmarshalText(text []byte) error {
	q, err := MessageTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

type VisibilityOperation int64

const (
	VisibilityOperation_RecordStarted          VisibilityOperation = 0
	VisibilityOperation_RecordClosed           VisibilityOperation = 1
	VisibilityOperation_UpsertSearchAttributes VisibilityOperation = 2
)

func (p VisibilityOperation) String() string {
	switch p {
	case VisibilityOperation_RecordStarted:
		return "RecordStarted"
	case VisibilityOperation_RecordClosed:
		return "RecordClosed"
	case VisibilityOperation_UpsertSearchAttributes:
		return "UpsertSearchAttributes"
	}
	return "<UNSET>"
}

func VisibilityOperationFromString(s string) (VisibilityOperation, error) {
	switch s {
	case "RecordStarted":
		return VisibilityOperation_RecordStarted, nil
	case "RecordClosed":
		return VisibilityOperation_RecordClosed, nil
	case "UpsertSearchAttributes":
		return VisibilityOperation_UpsertSearchAttributes, nil
	}
	return VisibilityOperation(0), fmt.Errorf("not a valid VisibilityOperation string")
}

func VisibilityOperationPtr(v VisibilityOperation) *VisibilityOperation { return &v }

func (p VisibilityOperation) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *VisibilityOperation) UnmarshalText(text []byte) error {
	q, err := VisibilityOperationFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

type FieldType int64

const (
	FieldType_String FieldType = 0
	FieldType_Int    FieldType = 1
	FieldType_Bool   FieldType = 2
	FieldType_Binary FieldType = 3
)

func (p FieldType) String() string {
	switch p {
	case FieldType_String:
		return "String"
	case FieldType_Int:
		return "Int"
	case FieldType_Bool:
		return "Bool"
	case FieldType_Binary:
		return "Binary"
	}
	return "<UNSET>"
}

func FieldTypeFromString(s string) (FieldType, error) {
	switch s {
	case "String":
		return FieldType_String, nil
	case "Int":
		return FieldType_Int, nil
	case "Bool":
		return FieldType_Bool, nil
	case "Binary":
		return FieldType_Binary, nil
	}
	return FieldType(0), fmt.Errorf("not a valid FieldType string")
}

func FieldTypePtr(v FieldType) *FieldType { return &v }

func (p FieldType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *FieldType) UnmarshalText(text []byte) error {
	q, err := FieldTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

// Attributes:
//   - Type
//   - StringData
//   - IntData
//   - BoolData
//   - BinaryData
type Field struct {
	// unused fields # 1 to 9
	Type *FieldType `thrift:"type,10" json:"type,omitempty"`
	// unused fields # 11 to 19
	StringData *string `thrift:"stringData,20" json:"stringData,omitempty"`
	// unused fields # 21 to 29
	IntData *int64 `thrift:"intData,30" json:"intData,omitempty"`
	// unused fields # 31 to 39
	BoolData *bool `thrift:"boolData,40" json:"boolData,omitempty"`
	// unused fields # 41 to 49
	BinaryData []byte `thrift:"binaryData,50" json:"binaryData,omitempty"`
}

func NewField() *Field {
	return &Field{}
}

var Field_Type_DEFAULT FieldType

func (p *Field) GetType() FieldType {
	if !p.IsSetType() {
		return Field_Type_DEFAULT
	}
	return *p.Type
}

var Field_StringData_DEFAULT string

func (p *Field) GetStringData() string {
	if !p.IsSetStringData() {
		return Field_StringData_DEFAULT
	}
	return *p.StringData
}

var Field_IntData_DEFAULT int64

func (p *Field) GetIntData() int64 {
	if !p.IsSetIntData() {
		return Field_IntData_DEFAULT
	}
	return *p.IntData
}

var Field_BoolData_DEFAULT bool

func (p *Field) GetBoolData() bool {
	if !p.IsSetBoolData() {
		return Field_BoolData_DEFAULT
	}
	return *p.BoolData
}

var Field_BinaryData_DEFAULT []byte

func (p *Field) GetBinaryData() []byte {
	return p.BinaryData
}
func (p *Field) IsSetType() bool {
	return p.Type != nil
}

func (p *Field) IsSetStringData() bool {
	return p.StringData != nil
}

func (p *Field) IsSetIntData() bool {
	return p.IntData != nil
}

func (p *Field) IsSetBoolData() bool {
	return p.BoolData != nil
}

func (p *Field) IsSetBinaryData() bool {
	return p.BinaryData != nil
}

func (p *Field) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		case 30:
			if err := p.readField30(iprot); err != nil {
				return err
			}
		case 40:
			if err := p.readField40(iprot); err != nil {
				return err
			}
		case 50:
			if err := p.readField50(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Field) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		temp := FieldType(v)
		p.Type = &temp
	}
	return nil
}

func (p *Field) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.StringData = &v
	}
	return nil
}

func (p *Field) readField30(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 30: ", err)
	} else {
		p.IntData = &v
	}
	return nil
}

func (p *Field) readField40(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return thrift.PrependError("error reading field 40: ", err)
	} else {
		p.BoolData = &v
	}
	return nil
}

func (p *Field) readField50(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return thrift.PrependError("error reading field 50: ", err)
	} else {
		p.BinaryData = v
	}
	return nil
}

func (p *Field) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Field"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := p.writeField30(oprot); err != nil {
		return err
	}
	if err := p.writeField40(oprot); err != nil {
		return err
	}
	if err := p.writeField50(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Field) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetType() {
		if err := oprot.WriteFieldBegin("type", thrift.I32, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:type: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.Type)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.type (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:type: ", p), err)
		}
	}
	return err
}

func (p *Field) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetStringData() {
		if err := oprot.WriteFieldBegin("stringData", thrift.STRING, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:stringData: ", p), err)
		}
		if err := oprot.WriteString(string(*p.StringData)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.stringData (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:stringData: ", p), err)
		}
	}
	return err
}

func (p *Field) writeField30(oprot thrift.TProtocol) (err error) {
	if p.IsSetIntData() {
		if err := oprot.WriteFieldBegin("intData", thrift.I64, 30); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 30:intData: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.IntData)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.intData (30) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 30:intData: ", p), err)
		}
	}
	return err
}

func (p *Field) writeField40(oprot thrift.TProtocol) (err error) {
	if p.IsSetBoolData() {
		if err := oprot.WriteFieldBegin("boolData", thrift.BOOL, 40); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 40:boolData: ", p), err)
		}
		if err := oprot.WriteBool(bool(*p.BoolData)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.boolData (40) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 40:boolData: ", p), err)
		}
	}
	return err
}

func (p *Field) writeField50(oprot thrift.TProtocol) (err error) {
	if p.IsSetBinaryData() {
		if err := oprot.WriteFieldBegin("binaryData", thrift.STRING, 50); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 50:binaryData: ", p), err)
		}
		if err := oprot.WriteBinary(p.BinaryData); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.binaryData (50) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 50:binaryData: ", p), err)
		}
	}
	return err
}

func (p *Field) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Field(%+v)", *p)
}

// Attributes:
//   - MessageType
//   - DomainID
//   - WorkflowID
//   - RunID
//   - Version
//   - Fields
//   - VisibilityOperation
type Message struct {
	// unused fields # 1 to 9
	MessageType *MessageType `thrift:"messageType,10" json:"messageType,omitempty"`
	// unused fields # 11 to 19
	DomainID *string `thrift:"domainID,20" json:"domainID,omitempty"`
	// unused fields # 21 to 29
	WorkflowID *string `thrift:"workflowID,30" json:"workflowID,omitempty"`
	// unused fields # 31 to 39
	RunID *string `thrift:"runID,40" json:"runID,omitempty"`
	// unused fields # 41 to 49
	Version *int64 `thrift:"version,50" json:"version,omitempty"`
	// unused fields # 51 to 59
	Fields map[string]*Field `thrift:"fields,60" json:"fields,omitempty"`
	// unused fields # 61 to 69
	VisibilityOperation *VisibilityOperation `thrift:"visibilityOperation,70" json:"visibilityOperation,omitempty"`
}

func NewMessage() *Message {
	return &Message{}
}

var Message_MessageType_DEFAULT MessageType

func (p *Message) GetMessageType() MessageType {
	if !p.IsSetMessageType() {
		return Message_MessageType_DEFAULT
	}
	return *p.MessageType
}

var Message_DomainID_DEFAULT string

func (p *Message) GetDomainID() string {
	if !p.IsSetDomainID() {
		return Message_DomainID_DEFAULT
	}
	return *p.DomainID
}

var Message_WorkflowID_DEFAULT string

func (p *Message) GetWorkflowID() string {
	if !p.IsSetWorkflowID() {
		return Message_WorkflowID_DEFAULT
	}
	return *p.WorkflowID
}

var Message_RunID_DEFAULT string

func (p *Message) GetRunID() string {
	if !p.IsSetRunID() {
		return Message_RunID_DEFAULT
	}
	return *p.RunID
}

var Message_Version_DEFAULT int64

func (p *Message) GetVersion() int64 {
	if !p.IsSetVersion() {
		return Message_Version_DEFAULT
	}
	return *p.Version
}

var Message_Fields_DEFAULT map[string]*Field

func (p *Message) GetFields() map[string]*Field {
	return p.Fields
}

var Message_VisibilityOperation_DEFAULT VisibilityOperation

func (p *Message) GetVisibilityOperation() VisibilityOperation {
	if !p.IsSetVisibilityOperation() {
		return Message_VisibilityOperation_DEFAULT
	}
	return *p.VisibilityOperation
}
func (p *Message) IsSetMessageType() bool {
	return p.MessageType != nil
}

func (p *Message) IsSetDomainID() bool {
	return p.DomainID != nil
}

func (p *Message) IsSetWorkflowID() bool {
	return p.WorkflowID != nil
}

func (p *Message) IsSetRunID() bool {
	return p.RunID != nil
}

func (p *Message) IsSetVersion() bool {
	return p.Version != nil
}

func (p *Message) IsSetFields() bool {
	return p.Fields != nil
}

func (p *Message) IsSetVisibilityOperation() bool {
	return p.VisibilityOperation != nil
}

func (p *Message) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		case 30:
			if err := p.readField30(iprot); err != nil {
				return err
			}
		case 40:
			if err := p.readField40(iprot); err != nil {
				return err
			}
		case 50:
			if err := p.readField50(iprot); err != nil {
				return err
			}
		case 60:
			if err := p.readField60(iprot); err != nil {
				return err
			}
		case 70:
			if err := p.readField70(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Message) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		temp := MessageType(v)
		p.MessageType = &temp
	}
	return nil
}

func (p *Message) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.DomainID = &v
	}
	return nil
}

func (p *Message) readField30(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 30: ", err)
	} else {
		p.WorkflowID = &v
	}
	return nil
}

func (p *Message) readField40(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 40: ", err)
	} else {
		p.RunID = &v
	}
	return nil
}

func (p *Message) readField50(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 50: ", err)
	} else {
		p.Version = &v
	}
	return nil
}

func (p *Message) readField60(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]*Field, size)
	p.Fields = tMap
	for i := 0; i < size; i++ {
		var _key0 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key0 = v
		}
		_val1 := &Field{}
		if err := _val1.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val1), err)
		}
		p.Fields[_key0] = _val1
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *Message) readField70(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 70: ", err)
	} else {
		temp := VisibilityOperation(v)
		p.VisibilityOperation = &temp
	}
	return nil
}

func (p *Message) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("Message"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := p.writeField30(oprot); err != nil {
		return err
	}
	if err := p.writeField40(oprot); err != nil {
		return err
	}
	if err := p.writeField50(oprot); err != nil {
		return err
	}
	if err := p.writeField60(oprot); err != nil {
		return err
	}
	if err := p.writeField70(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Message) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetMessageType() {
		if err := oprot.WriteFieldBegin("messageType", thrift.I32, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:messageType: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.MessageType)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.messageType (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:messageType: ", p), err)
		}
	}
	return err
}

func (p *Message) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetDomainID() {
		if err := oprot.WriteFieldBegin("domainID", thrift.STRING, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:domainID: ", p), err)
		}
		if err := oprot.WriteString(string(*p.DomainID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.domainID (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:domainID: ", p), err)
		}
	}
	return err
}

func (p *Message) writeField30(oprot thrift.TProtocol) (err error) {
	if p.IsSetWorkflowID() {
		if err := oprot.WriteFieldBegin("workflowID", thrift.STRING, 30); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 30:workflowID: ", p), err)
		}
		if err := oprot.WriteString(string(*p.WorkflowID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.workflowID (30) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 30:workflowID: ", p), err)
		}
	}
	return err
}

func (p *Message) writeField40(oprot thrift.TProtocol) (err error) {
	if p.IsSetRunID() {
		if err := oprot.WriteFieldBegin("runID", thrift.STRING, 40); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 40:runID: ", p), err)
		}
		if err := oprot.WriteString(string(*p.RunID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.runID (40) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 40:runID: ", p), err)
		}
	}
	return err
}

func (p *Message) writeField50(oprot thrift.TProtocol) (err error) {
	if p.IsSetVersion() {
		if err := oprot.WriteFieldBegin("version", thrift.I64, 50); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 50:version: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.Version)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.version (50) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 50:version: ", p), err)
		}
	}
	return err
}

func (p *Message) writeField60(oprot thrift.TProtocol) (err error) {
	if p.IsSetFields() {
		if err := oprot.WriteFieldBegin("fields", thrift.MAP, 60); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 60:fields: ", p), err)
		}
		if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRUCT, len(p.Fields)); err != nil {
			return thrift.PrependError("error writing map begin: ", err)
		}
		for k, v := range p.Fields {
			if err := oprot.WriteString(string(k)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
			if err := v.Write(oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return thrift.PrependError("error writing map end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 60:fields: ", p), err)
		}
	}
	return err
}

func (p *Message) writeField70(oprot thrift.TProtocol) (err error) {
	if p.IsSetVisibilityOperation() {
		if err := oprot.WriteFieldBegin("visibilityOperation", thrift.I32, 70); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 70:visibilityOperation: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.VisibilityOperation)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.visibilityOperation (70) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 70:visibilityOperation: ", p), err)
		}
	}
	return err
}

func (p *Message) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message(%+v)", *p)
}

// Attributes:
//   - WorkflowID
//   - Payload
type PinotMessage struct {
	// unused fields # 1 to 9
	WorkflowID *string `thrift:"workflowID,10" json:"workflowID,omitempty"`
	// unused fields # 11 to 19
	Payload []byte `thrift:"payload,20" json:"payload,omitempty"`
}

func NewPinotMessage() *PinotMessage {
	return &PinotMessage{}
}

var PinotMessage_WorkflowID_DEFAULT string

func (p *PinotMessage) GetWorkflowID() string {
	if !p.IsSetWorkflowID() {
		return PinotMessage_WorkflowID_DEFAULT
	}
	return *p.WorkflowID
}

var PinotMessage_Payload_DEFAULT []byte

func (p *PinotMessage) GetPayload() []byte {
	return p.Payload
}
func (p *PinotMessage) IsSetWorkflowID() bool {
	return p.WorkflowID != nil
}

func (p *PinotMessage) IsSetPayload() bool {
	return p.Payload != nil
}

func (p *PinotMessage) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *PinotMessage) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.WorkflowID = &v
	}
	return nil
}

func (p *PinotMessage) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.Payload = v
	}
	return nil
}

func (p *PinotMessage) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("PinotMessage"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *PinotMessage) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetWorkflowID() {
		if err := oprot.WriteFieldBegin("workflowID", thrift.STRING, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:workflowID: ", p), err)
		}
		if err := oprot.WriteString(string(*p.WorkflowID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.workflowID (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:workflowID: ", p), err)
		}
	}
	return err
}

func (p *PinotMessage) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetPayload() {
		if err := oprot.WriteFieldBegin("payload", thrift.STRING, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:payload: ", p), err)
		}
		if err := oprot.WriteBinary(p.Payload); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.payload (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:payload: ", p), err)
		}
	}
	return err
}

func (p *PinotMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PinotMessage(%+v)", *p)
}
