// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"admin"
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  DescribeWorkflowExecutionResponse DescribeWorkflowExecution(DescribeWorkflowExecutionRequest request)")
	fmt.Fprintln(os.Stderr, "  DescribeShardDistributionResponse DescribeShardDistribution(DescribeShardDistributionRequest request)")
	fmt.Fprintln(os.Stderr, "  DescribeHistoryHostResponse DescribeHistoryHost(DescribeHistoryHostRequest request)")
	fmt.Fprintln(os.Stderr, "  void CloseShard(CloseShardRequest request)")
	fmt.Fprintln(os.Stderr, "  void RemoveTask(RemoveTaskRequest request)")
	fmt.Fprintln(os.Stderr, "  void ResetQueue(ResetQueueRequest request)")
	fmt.Fprintln(os.Stderr, "  DescribeQueueResponse DescribeQueue(DescribeQueueRequest request)")
	fmt.Fprintln(os.Stderr, "  GetWorkflowExecutionRawHistoryV2Response GetWorkflowExecutionRawHistoryV2(GetWorkflowExecutionRawHistoryV2Request getRequest)")
	fmt.Fprintln(os.Stderr, "  GetReplicationMessagesResponse GetReplicationMessages(GetReplicationMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  GetDomainReplicationMessagesResponse GetDomainReplicationMessages(GetDomainReplicationMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  GetDLQReplicationMessagesResponse GetDLQReplicationMessages(GetDLQReplicationMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  void ReapplyEvents(ReapplyEventsRequest reapplyEventsRequest)")
	fmt.Fprintln(os.Stderr, "  void AddSearchAttribute(AddSearchAttributeRequest request)")
	fmt.Fprintln(os.Stderr, "  DescribeClusterResponse DescribeCluster()")
	fmt.Fprintln(os.Stderr, "  ReadDLQMessagesResponse ReadDLQMessages(ReadDLQMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  void PurgeDLQMessages(PurgeDLQMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  MergeDLQMessagesResponse MergeDLQMessages(MergeDLQMessagesRequest request)")
	fmt.Fprintln(os.Stderr, "  CountHistoryTaskDLQTasksResponse CountHistoryTaskDLQTasks(CountHistoryTaskDLQTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  GetHistoryTaskDLQAckLevelsResponse GetHistoryTaskDLQAckLevels(GetHistoryTaskDLQAckLevelsRequest request)")
	fmt.Fprintln(os.Stderr, "  ReadHistoryTaskDLQTasksResponse ReadHistoryTaskDLQTasks(ReadHistoryTaskDLQTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  void RefreshWorkflowTasks(RefreshWorkflowTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  void ResendReplicationTasks(ResendReplicationTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  GetCrossClusterTasksResponse GetCrossClusterTasks(GetCrossClusterTasksRequest request)")
	fmt.Fprintln(os.Stderr, "  RespondCrossClusterTasksCompletedResponse RespondCrossClusterTasksCompleted(RespondCrossClusterTasksCompletedRequest request)")
	fmt.Fprintln(os.Stderr, "  GetDynamicConfigResponse GetDynamicConfig(GetDynamicConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  void UpdateDynamicConfig(UpdateDynamicConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  void RestoreDynamicConfig(RestoreDynamicConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  ListDynamicConfigResponse ListDynamicConfig(ListDynamicConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  GetOperationalDynamicConfigResponse GetOperationalDynamicConfig(GetOperationalDynamicConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  void UpdateOperationalDynamicConfig(UpdateOperationalDynamicConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  void RestoreOperationalDynamicConfig(RestoreOperationalDynamicConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  ListOperationalDynamicConfigResponse ListOperationalDynamicConfig(ListOperationalDynamicConfigRequest request)")
	fmt.Fprintln(os.Stderr, "  AdminDeleteWorkflowResponse DeleteWorkflow(AdminDeleteWorkflowRequest request)")
	fmt.Fprintln(os.Stderr, "  AdminMaintainWorkflowResponse MaintainCorruptWorkflow(AdminMaintainWorkflowRequest request)")
	fmt.Fprintln(os.Stderr, "  GetGlobalIsolationGroupsResponse GetGlobalIsolationGroups(GetGlobalIsolationGroupsRequest request)")
	fmt.Fprintln(os.Stderr, "  UpdateGlobalIsolationGroupsResponse UpdateGlobalIsolationGroups(UpdateGlobalIsolationGroupsRequest request)")
	fmt.Fprintln(os.Stderr, "  GetDomainIsolationGroupsResponse GetDomainIsolationGroups(GetDomainIsolationGroupsRequest request)")
	fmt.Fprintln(os.Stderr, "  UpdateDomainIsolationGroupsResponse UpdateDomainIsolationGroups(UpdateDomainIsolationGroupsRequest request)")
	fmt.Fprintln(os.Stderr, "  GetDomainAsyncWorkflowConfiguratonResponse GetDomainAsyncWorkflowConfiguraton(GetDomainAsyncWorkflowConfiguratonRequest request)")
	fmt.Fprintln(os.Stderr, "  UpdateDomainAsyncWorkflowConfiguratonResponse UpdateDomainAsyncWorkflowConfiguraton(UpdateDomainAsyncWorkflowConfiguratonRequest request)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := admin.NewAdminServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "DescribeWorkflowExecution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeWorkflowExecution requires 1 args")
			flag.Usage()
		}
		arg100 := flag.Arg(1)
		mbTrans101 := thrift.NewTMemoryBufferLen(len(arg100))
		defer mbTrans101.Close()
		_, err102 := mbTrans101.WriteString(arg100)
		if err102 != nil {
			Usage()
			return
		}
		factory103 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt104 := factory103.GetProtocol(mbTrans101)
		argvalue0 := admin.NewDescribeWorkflowExecutionRequest()
		err105 := argvalue0.Read(jsProt104)
		if err105 != nil {
			Usage()
			return
		}
		value0 := admin.DescribeWorkflowExecutionRequest(argvalue0)
		fmt.Print(client.DescribeWorkflowExecution(value0))
		fmt.Print("\n")
		break
	case "DescribeShardDistribution":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeShardDistribution requires 1 args")
			flag.Usage()
		}
		arg106 := flag.Arg(1)
		mbTrans107 := thrift.NewTMemoryBufferLen(len(arg106))
		defer mbTrans107.Close()
		_, err108 := mbTrans107.WriteString(arg106)
		if err108 != nil {
			Usage()
			return
		}
		factory109 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt110 := factory109.GetProtocol(mbTrans107)
		argvalue0 := admin.NewDescribeShardDistributionRequest()
		err111 := argvalue0.Read(jsProt110)
		if err111 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeShardDistribution(value0))
		fmt.Print("\n")
		break
	case "DescribeHistoryHost":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeHistoryHost requires 1 args")
			flag.Usage()
		}
		arg112 := flag.Arg(1)
		mbTrans113 := thrift.NewTMemoryBufferLen(len(arg112))
		defer mbTrans113.Close()
		_, err114 := mbTrans113.WriteString(arg112)
		if err114 != nil {
			Usage()
			return
		}
		factory115 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt116 := factory115.GetProtocol(mbTrans113)
		argvalue0 := admin.NewDescribeHistoryHostRequest()
		err117 := argvalue0.Read(jsProt116)
		if err117 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeHistoryHost(value0))
		fmt.Print("\n")
		break
	case "CloseShard":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CloseShard requires 1 args")
			flag.Usage()
		}
		arg118 := flag.Arg(1)
		mbTrans119 := thrift.NewTMemoryBufferLen(len(arg118))
		defer mbTrans119.Close()
		_, err120 := mbTrans119.WriteString(arg118)
		if err120 != nil {
			Usage()
			return
		}
		factory121 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt122 := factory121.GetProtocol(mbTrans119)
		argvalue0 := admin.NewCloseShardRequest()
		err123 := argvalue0.Read(jsProt122)
		if err123 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CloseShard(value0))
		fmt.Print("\n")
		break
	case "RemoveTask":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RemoveTask requires 1 args")
			flag.Usage()
		}
		arg124 := flag.Arg(1)
		mbTrans125 := thrift.NewTMemoryBufferLen(len(arg124))
		defer mbTrans125.Close()
		_, err126 := mbTrans125.WriteString(arg124)
		if err126 != nil {
			Usage()
			return
		}
		factory127 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt128 := factory127.GetProtocol(mbTrans125)
		argvalue0 := admin.NewRemoveTaskRequest()
		err129 := argvalue0.Read(jsProt128)
		if err129 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RemoveTask(value0))
		fmt.Print("\n")
		break
	case "ResetQueue":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ResetQueue requires 1 args")
			flag.Usage()
		}
		arg130 := flag.Arg(1)
		mbTrans131 := thrift.NewTMemoryBufferLen(len(arg130))
		defer mbTrans131.Close()
		_, err132 := mbTrans131.WriteString(arg130)
		if err132 != nil {
			Usage()
			return
		}
		factory133 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt134 := factory133.GetProtocol(mbTrans131)
		argvalue0 := admin.NewResetQueueRequest()
		err135 := argvalue0.Read(jsProt134)
		if err135 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ResetQueue(value0))
		fmt.Print("\n")
		break
	case "DescribeQueue":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeQueue requires 1 args")
			flag.Usage()
		}
		arg136 := flag.Arg(1)
		mbTrans137 := thrift.NewTMemoryBufferLen(len(arg136))
		defer mbTrans137.Close()
		_, err138 := mbTrans137.WriteString(arg136)
		if err138 != nil {
			Usage()
			return
		}
		factory139 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt140 := factory139.GetProtocol(mbTrans137)
		argvalue0 := admin.NewDescribeQueueRequest()
		err141 := argvalue0.Read(jsProt140)
		if err141 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DescribeQueue(value0))
		fmt.Print("\n")
		break
	case "GetWorkflowExecutionRawHistoryV2":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetWorkflowExecutionRawHistoryV2 requires 1 args")
			flag.Usage()
		}
		arg142 := flag.Arg(1)
		mbTrans143 := thrift.NewTMemoryBufferLen(len(arg142))
		defer mbTrans143.Close()
		_, err144 := mbTrans143.WriteString(arg142)
		if err144 != nil {
			Usage()
			return
		}
		factory145 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt146 := factory145.GetProtocol(mbTrans143)
		argvalue0 := admin.NewGetWorkflowExecutionRawHistoryV2Request()
		err147 := argvalue0.Read(jsProt146)
		if err147 != nil {
			Usage()
			return
		}
		value0 := admin.GetWorkflowExecutionRawHistoryV2Request(argvalue0)
		fmt.Print(client.GetWorkflowExecutionRawHistoryV2(value0))
		fmt.Print("\n")
		break
	case "GetReplicationMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetReplicationMessages requires 1 args")
			flag.Usage()
		}
		arg148 := flag.Arg(1)
		mbTrans149 := thrift.NewTMemoryBufferLen(len(arg148))
		defer mbTrans149.Close()
		_, err150 := mbTrans149.WriteString(arg148)
		if err150 != nil {
			Usage()
			return
		}
		factory151 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt152 := factory151.GetProtocol(mbTrans149)
		argvalue0 := admin.NewGetReplicationMessagesRequest()
		err153 := argvalue0.Read(jsProt152)
		if err153 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetReplicationMessages(value0))
		fmt.Print("\n")
		break
	case "GetDomainReplicationMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDomainReplicationMessages requires 1 args")
			flag.Usage()
		}
		arg154 := flag.Arg(1)
		mbTrans155 := thrift.NewTMemoryBufferLen(len(arg154))
		defer mbTrans155.Close()
		_, err156 := mbTrans155.WriteString(arg154)
		if err156 != nil {
			Usage()
			return
		}
		factory157 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt158 := factory157.GetProtocol(mbTrans155)
		argvalue0 := admin.NewGetDomainReplicationMessagesRequest()
		err159 := argvalue0.Read(jsProt158)
		if err159 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetDomainReplicationMessages(value0))
		fmt.Print("\n")
		break
	case "GetDLQReplicationMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDLQReplicationMessages requires 1 args")
			flag.Usage()
		}
		arg160 := flag.Arg(1)
		mbTrans161 := thrift.NewTMemoryBufferLen(len(arg160))
		defer mbTrans161.Close()
		_, err162 := mbTrans161.WriteString(arg160)
		if err162 != nil {
			Usage()
			return
		}
		factory163 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt164 := factory163.GetProtocol(mbTrans161)
		argvalue0 := admin.NewGetDLQReplicationMessagesRequest()
		err165 := argvalue0.Read(jsProt164)
		if err165 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetDLQReplicationMessages(value0))
		fmt.Print("\n")
		break
	case "ReapplyEvents":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ReapplyEvents requires 1 args")
			flag.Usage()
		}
		arg166 := flag.Arg(1)
		mbTrans167 := thrift.NewTMemoryBufferLen(len(arg166))
		defer mbTrans167.Close()
		_, err168 := mbTrans167.WriteString(arg166)
		if err168 != nil {
			Usage()
			return
		}
		factory169 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt170 := factory169.GetProtocol(mbTrans167)
		argvalue0 := admin.NewReapplyEventsRequest()
		err171 := argvalue0.Read(jsProt170)
		if err171 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ReapplyEvents(value0))
		fmt.Print("\n")
		break
	case "AddSearchAttribute":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "AddSearchAttribute requires 1 args")
			flag.Usage()
		}
		arg172 := flag.Arg(1)
		mbTrans173 := thrift.NewTMemoryBufferLen(len(arg172))
		defer mbTrans173.Close()
		_, err174 := mbTrans173.WriteString(arg172)
		if err174 != nil {
			Usage()
			return
		}
		factory175 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt176 := factory175.GetProtocol(mbTrans173)
		argvalue0 := admin.NewAddSearchAttributeRequest()
		err177 := argvalue0.Read(jsProt176)
		if err177 != nil {
			Usage()
			return
		}
		value0 := admin.AddSearchAttributeRequest(argvalue0)
		fmt.Print(client.AddSearchAttribute(value0))
		fmt.Print("\n")
		break
	case "DescribeCluster":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "DescribeCluster requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.DescribeCluster())
		fmt.Print("\n")
		break
	case "ReadDLQMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ReadDLQMessages requires 1 args")
			flag.Usage()
		}
		arg178 := flag.Arg(1)
		mbTrans179 := thrift.NewTMemoryBufferLen(len(arg178))
		defer mbTrans179.Close()
		_, err180 := mbTrans179.WriteString(arg178)
		if err180 != nil {
			Usage()
			return
		}
		factory181 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt182 := factory181.GetProtocol(mbTrans179)
		argvalue0 := admin.NewReadDLQMessagesRequest()
		err183 := argvalue0.Read(jsProt182)
		if err183 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ReadDLQMessages(value0))
		fmt.Print("\n")
		break
	case "PurgeDLQMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "PurgeDLQMessages requires 1 args")
			flag.Usage()
		}
		arg184 := flag.Arg(1)
		mbTrans185 := thrift.NewTMemoryBufferLen(len(arg184))
		defer mbTrans185.Close()
		_, err186 := mbTrans185.WriteString(arg184)
		if err186 != nil {
			Usage()
			return
		}
		factory187 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt188 := factory187.GetProtocol(mbTrans185)
		argvalue0 := admin.NewPurgeDLQMessagesRequest()
		err189 := argvalue0.Read(jsProt188)
		if err189 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.PurgeDLQMessages(value0))
		fmt.Print("\n")
		break
	case "MergeDLQMessages":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MergeDLQMessages requires 1 args")
			flag.Usage()
		}
		arg190 := flag.Arg(1)
		mbTrans191 := thrift.NewTMemoryBufferLen(len(arg190))
		defer mbTrans191.Close()
		_, err192 := mbTrans191.WriteString(arg190)
		if err192 != nil {
			Usage()
			return
		}
		factory193 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt194 := factory193.GetProtocol(mbTrans191)
		argvalue0 := admin.NewMergeDLQMessagesRequest()
		err195 := argvalue0.Read(jsProt194)
		if err195 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.MergeDLQMessages(value0))
		fmt.Print("\n")
		break
	case "CountHistoryTaskDLQTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CountHistoryTaskDLQTasks requires 1 args")
			flag.Usage()
		}
		arg196 := flag.Arg(1)
		mbTrans197 := thrift.NewTMemoryBufferLen(len(arg196))
		defer mbTrans197.Close()
		_, err198 := mbTrans197.WriteString(arg196)
		if err198 != nil {
			Usage()
			return
		}
		factory199 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt200 := factory199.GetProtocol(mbTrans197)
		argvalue0 := admin.NewCountHistoryTaskDLQTasksRequest()
		err201 := argvalue0.Read(jsProt200)
		if err201 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountHistoryTaskDLQTasks(value0))
		fmt.Print("\n")
		break
	case "GetHistoryTaskDLQAckLevels":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetHistoryTaskDLQAckLevels requires 1 args")
			flag.Usage()
		}
		arg202 := flag.Arg(1)
		mbTrans203 := thrift.NewTMemoryBufferLen(len(arg202))
		defer mbTrans203.Close()
		_, err204 := mbTrans203.WriteString(arg202)
		if err204 != nil {
			Usage()
			return
		}
		factory205 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt206 := factory205.GetProtocol(mbTrans203)
		argvalue0 := admin.NewGetHistoryTaskDLQAckLevelsRequest()
		err207 := argvalue0.Read(jsProt206)
		if err207 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetHistoryTaskDLQAckLevels(value0))
		fmt.Print("\n")
		break
	case "ReadHistoryTaskDLQTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ReadHistoryTaskDLQTasks requires 1 args")
			flag.Usage()
		}
		arg208 := flag.Arg(1)
		mbTrans209 := thrift.NewTMemoryBufferLen(len(arg208))
		defer mbTrans209.Close()
		_, err210 := mbTrans209.WriteString(arg208)
		if err210 != nil {
			Usage()
			return
		}
		factory211 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt212 := factory211.GetProtocol(mbTrans209)
		argvalue0 := admin.NewReadHistoryTaskDLQTasksRequest()
		err213 := argvalue0.Read(jsProt212)
		if err213 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ReadHistoryTaskDLQTasks(value0))
		fmt.Print("\n")
		break
	case "RefreshWorkflowTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RefreshWorkflowTasks requires 1 args")
			flag.Usage()
		}
		arg214 := flag.Arg(1)
		mbTrans215 := thrift.NewTMemoryBufferLen(len(arg214))
		defer mbTrans215.Close()
		_, err216 := mbTrans215.WriteString(arg214)
		if err216 != nil {
			Usage()
			return
		}
		factory217 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt218 := factory217.GetProtocol(mbTrans215)
		argvalue0 := admin.NewRefreshWorkflowTasksRequest()
		err219 := argvalue0.Read(jsProt218)
		if err219 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RefreshWorkflowTasks(value0))
		fmt.Print("\n")
		break
	case "ResendReplicationTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ResendReplicationTasks requires 1 args")
			flag.Usage()
		}
		arg220 := flag.Arg(1)
		mbTrans221 := thrift.NewTMemoryBufferLen(len(arg220))
		defer mbTrans221.Close()
		_, err222 := mbTrans221.WriteString(arg220)
		if err222 != nil {
			Usage()
			return
		}
		factory223 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt224 := factory223.GetProtocol(mbTrans221)
		argvalue0 := admin.NewResendReplicationTasksRequest()
		err225 := argvalue0.Read(jsProt224)
		if err225 != nil {
			Usage()
			return
		}
		value0 := admin.ResendReplicationTasksRequest(argvalue0)
		fmt.Print(client.ResendReplicationTasks(value0))
		fmt.Print("\n")
		break
	case "GetCrossClusterTasks":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetCrossClusterTasks requires 1 args")
			flag.Usage()
		}
		arg226 := flag.Arg(1)
		mbTrans227 := thrift.NewTMemoryBufferLen(len(arg226))
		defer mbTrans227.Close()
		_, err228 := mbTrans227.WriteString(arg226)
		if err228 != nil {
			Usage()
			return
		}
		factory229 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt230 := factory229.GetProtocol(mbTrans227)
		argvalue0 := admin.NewGetCrossClusterTasksRequest()
		err231 := argvalue0.Read(jsProt230)
		if err231 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetCrossClusterTasks(value0))
		fmt.Print("\n")
		break
	case "RespondCrossClusterTasksCompleted":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RespondCrossClusterTasksCompleted requires 1 args")
			flag.Usage()
		}
		arg232 := flag.Arg(1)
		mbTrans233 := thrift.NewTMemoryBufferLen(len(arg232))
		defer mbTrans233.Close()
		_, err234 := mbTrans233.WriteString(arg232)
		if err234 != nil {
			Usage()
			return
		}
		factory235 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt236 := factory235.GetProtocol(mbTrans233)
		argvalue0 := admin.NewRespondCrossClusterTasksCompletedRequest()
		err237 := argvalue0.Read(jsProt236)
		if err237 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RespondCrossClusterTasksCompleted(value0))
		fmt.Print("\n")
		break
	case "GetDynamicConfig":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDynamicConfig requires 1 args")
			flag.Usage()
		}
		arg238 := flag.Arg(1)
		mbTrans239 := thrift.NewTMemoryBufferLen(len(arg238))
		defer mbTrans239.Close()
		_, err240 := mbTrans239.WriteString(arg238)
		if err240 != nil {
			Usage()
			return
		}
		factory241 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt242 := factory241.GetProtocol(mbTrans239)
		argvalue0 := admin.NewGetDynamicConfigRequest()
		err243 := argvalue0.Read(jsProt242)
		if err243 != nil {
			Usage()
			return
		}
		value0 := admin.GetDynamicConfigRequest(argvalue0)
		fmt.Print(client.GetDynamicConfig(value0))
		fmt.Print("\n")
		break
	case "UpdateDynamicConfig":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateDynamicConfig requires 1 args")
			flag.Usage()
		}
		arg244 := flag.Arg(1)
		mbTrans245 := thrift.NewTMemoryBufferLen(len(arg244))
		defer mbTrans245.Close()
		_, err246 := mbTrans245.WriteString(arg244)
		if err246 != nil {
			Usage()
			return
		}
		factory247 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt248 := factory247.GetProtocol(mbTrans245)
		argvalue0 := admin.NewUpdateDynamicConfigRequest()
		err249 := argvalue0.Read(jsProt248)
		if err249 != nil {
			Usage()
			return
		}
		value0 := admin.UpdateDynamicConfigRequest(argvalue0)
		fmt.Print(client.UpdateDynamicConfig(value0))
		fmt.Print("\n")
		break
	case "RestoreDynamicConfig":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RestoreDynamicConfig requires 1 args")
			flag.Usage()
		}
		arg250 := flag.Arg(1)
		mbTrans251 := thrift.NewTMemoryBufferLen(len(arg250))
		defer mbTrans251.Close()
		_, err252 := mbTrans251.WriteString(arg250)
		if err252 != nil {
			Usage()
			return
		}
		factory253 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt254 := factory253.GetProtocol(mbTrans251)
		argvalue0 := admin.NewRestoreDynamicConfigRequest()
		err255 := argvalue0.Read(jsProt254)
		if err255 != nil {
			Usage()
			return
		}
		value0 := admin.RestoreDynamicConfigRequest(argvalue0)
		fmt.Print(client.RestoreDynamicConfig(value0))
		fmt.Print("\n")
		break
	case "ListDynamicConfig":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListDynamicConfig requires 1 args")
			flag.Usage()
		}
		arg256 := flag.Arg(1)
		mbTrans257 := thrift.NewTMemoryBufferLen(len(arg256))
		defer mbTrans257.Close()
		_, err258 := mbTrans257.WriteString(arg256)
		if err258 != nil {
			Usage()
			return
		}
		factory259 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt260 := factory259.GetProtocol(mbTrans257)
		argvalue0 := admin.NewListDynamicConfigRequest()
		err261 := argvalue0.Read(jsProt260)
		if err261 != nil {
			Usage()
			return
		}
		value0 := admin.ListDynamicConfigRequest(argvalue0)
		fmt.Print(client.ListDynamicConfig(value0))
		fmt.Print("\n")
		break
	case "GetOperationalDynamicConfig":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetOperationalDynamicConfig requires 1 args")
			flag.Usage()
		}
		arg262 := flag.Arg(1)
		mbTrans263 := thrift.NewTMemoryBufferLen(len(arg262))
		defer mbTrans263.Close()
		_, err264 := mbTrans263.WriteString(arg262)
		if err264 != nil {
			Usage()
			return
		}
		factory265 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt266 := factory265.GetProtocol(mbTrans263)
		argvalue0 := admin.NewGetOperationalDynamicConfigRequest()
		err267 := argvalue0.Read(jsProt266)
		if err267 != nil {
			Usage()
			return
		}
		value0 := admin.GetOperationalDynamicConfigRequest(argvalue0)
		fmt.Print(client.GetOperationalDynamicConfig(value0))
		fmt.Print("\n")
		break
	case "UpdateOperationalDynamicConfig":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateOperationalDynamicConfig requires 1 args")
			flag.Usage()
		}
		arg268 := flag.Arg(1)
		mbTrans269 := thrift.NewTMemoryBufferLen(len(arg268))
		defer mbTrans269.Close()
		_, err270 := mbTrans269.WriteString(arg268)
		if err270 != nil {
			Usage()
			return
		}
		factory271 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt272 := factory271.GetProtocol(mbTrans269)
		argvalue0 := admin.NewUpdateOperationalDynamicConfigRequest()
		err273 := argvalue0.Read(jsProt272)
		if err273 != nil {
			Usage()
			return
		}
		value0 := admin.UpdateOperationalDynamicConfigRequest(argvalue0)
		fmt.Print(client.UpdateOperationalDynamicConfig(value0))
		fmt.Print("\n")
		break
	case "RestoreOperationalDynamicConfig":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RestoreOperationalDynamicConfig requires 1 args")
			flag.Usage()
		}
		arg274 := flag.Arg(1)
		mbTrans275 := thrift.NewTMemoryBufferLen(len(arg274))
		defer mbTrans275.Close()
		_, err276 := mbTrans275.WriteString(arg274)
		if err276 != nil {
			Usage()
			return
		}
		factory277 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt278 := factory277.GetProtocol(mbTrans275)
		argvalue0 := admin.NewRestoreOperationalDynamicConfigRequest()
		err279 := argvalue0.Read(jsProt278)
		if err279 != nil {
			Usage()
			return
		}
		value0 := admin.RestoreOperationalDynamicConfigRequest(argvalue0)
		fmt.Print(client.RestoreOperationalDynamicConfig(value0))
		fmt.Print("\n")
		break
	case "ListOperationalDynamicConfig":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListOperationalDynamicConfig requires 1 args")
			flag.Usage()
		}
		arg280 := flag.Arg(1)
		mbTrans281 := thrift.NewTMemoryBufferLen(len(arg280))
		defer mbTrans281.Close()
		_, err282 := mbTrans281.WriteString(arg280)
		if err282 != nil {
			Usage()
			return
		}
		factory283 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt284 := factory283.GetProtocol(mbTrans281)
		argvalue0 := admin.NewListOperationalDynamicConfigRequest()
		err285 := argvalue0.Read(jsProt284)
		if err285 != nil {
			Usage()
			return
		}
		value0 := admin.ListOperationalDynamicConfigRequest(argvalue0)
		fmt.Print(client.ListOperationalDynamicConfig(value0))
		fmt.Print("\n")
		break
	case "DeleteWorkflow":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteWorkflow requires 1 args")
			flag.Usage()
		}
		arg286 := flag.Arg(1)
		mbTrans287 := thrift.NewTMemoryBufferLen(len(arg286))
		defer mbTrans287.Close()
		_, err288 := mbTrans287.WriteString(arg286)
		if err288 != nil {
			Usage()
			return
		}
		factory289 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt290 := factory289.GetProtocol(mbTrans287)
		argvalue0 := admin.NewAdminDeleteWorkflowRequest()
		err291 := argvalue0.Read(jsProt290)
		if err291 != nil {
			Usage()
			return
		}
		value0 := admin.AdminDeleteWorkflowRequest(argvalue0)
		fmt.Print(client.DeleteWorkflow(value0))
		fmt.Print("\n")
		break
	case "MaintainCorruptWorkflow":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "MaintainCorruptWorkflow requires 1 args")
			flag.Usage()
		}
		arg292 := flag.Arg(1)
		mbTrans293 := thrift.NewTMemoryBufferLen(len(arg292))
		defer mbTrans293.Close()
		_, err294 := mbTrans293.WriteString(arg292)
		if err294 != nil {
			Usage()
			return
		}
		factory295 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt296 := factory295.GetProtocol(mbTrans293)
		argvalue0 := admin.NewAdminMaintainWorkflowRequest()
		err297 := argvalue0.Read(jsProt296)
		if err297 != nil {
			Usage()
			return
		}
		value0 := admin.AdminMaintainWorkflowRequest(argvalue0)
		fmt.Print(client.MaintainCorruptWorkflow(value0))
		fmt.Print("\n")
		break
	case "GetGlobalIsolationGroups":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetGlobalIsolationGroups requires 1 args")
			flag.Usage()
		}
		arg298 := flag.Arg(1)
		mbTrans299 := thrift.NewTMemoryBufferLen(len(arg298))
		defer mbTrans299.Close()
		_, err300 := mbTrans299.WriteString(arg298)
		if err300 != nil {
			Usage()
			return
		}
		factory301 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt302 := factory301.GetProtocol(mbTrans299)
		argvalue0 := admin.NewGetGlobalIsolationGroupsRequest()
		err303 := argvalue0.Read(jsProt302)
		if err303 != nil {
			Usage()
			return
		}
		value0 := admin.GetGlobalIsolationGroupsRequest(argvalue0)
		fmt.Print(client.GetGlobalIsolationGroups(value0))
		fmt.Print("\n")
		break
	case "UpdateGlobalIsolationGroups":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateGlobalIsolationGroups requires 1 args")
			flag.Usage()
		}
		arg304 := flag.Arg(1)
		mbTrans305 := thrift.NewTMemoryBufferLen(len(arg304))
		defer mbTrans305.Close()
		_, err306 := mbTrans305.WriteString(arg304)
		if err306 != nil {
			Usage()
			return
		}
		factory307 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt308 := factory307.GetProtocol(mbTrans305)
		argvalue0 := admin.NewUpdateGlobalIsolationGroupsRequest()
		err309 := argvalue0.Read(jsProt308)
		if err309 != nil {
			Usage()
			return
		}
		value0 := admin.UpdateGlobalIsolationGroupsRequest(argvalue0)
		fmt.Print(client.UpdateGlobalIsolationGroups(value0))
		fmt.Print("\n")
		break
	case "GetDomainIsolationGroups":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDomainIsolationGroups requires 1 args")
			flag.Usage()
		}
		arg310 := flag.Arg(1)
		mbTrans311 := thrift.NewTMemoryBufferLen(len(arg310))
		defer mbTrans311.Close()
		_, err312 := mbTrans311.WriteString(arg310)
		if err312 != nil {
			Usage()
			return
		}
		factory313 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt314 := factory313.GetProtocol(mbTrans311)
		argvalue0 := admin.NewGetDomainIsolationGroupsRequest()
		err315 := argvalue0.Read(jsProt314)
		if err315 != nil {
			Usage()
			return
		}
		value0 := admin.GetDomainIsolationGroupsRequest(argvalue0)
		fmt.Print(client.GetDomainIsolationGroups(value0))
		fmt.Print("\n")
		break
	case "UpdateDomainIsolationGroups":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateDomainIsolationGroups requires 1 args")
			flag.Usage()
		}
		arg316 := flag.Arg(1)
		mbTrans317 := thrift.NewTMemoryBufferLen(len(arg316))
		defer mbTrans317.Close()
		_, err318 := mbTrans317.WriteString(arg316)
		if err318 != nil {
			Usage()
			return
		}
		factory319 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt320 := factory319.GetProtocol(mbTrans317)
		argvalue0 := admin.NewUpdateDomainIsolationGroupsRequest()
		err321 := argvalue0.Read(jsProt320)
		if err321 != nil {
			Usage()
			return
		}
		value0 := admin.UpdateDomainIsolationGroupsRequest(argvalue0)
		fmt.Print(client.UpdateDomainIsolationGroups(value0))
		fmt.Print("\n")
		break
	case "GetDomainAsyncWorkflowConfiguraton":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDomainAsyncWorkflowConfiguraton requires 1 args")
			flag.Usage()
		}
		arg322 := flag.Arg(1)
		mbTrans323 := thrift.NewTMemoryBufferLen(len(arg322))
		defer mbTrans323.Close()
		_, err324 := mbTrans323.WriteString(arg322)
		if err324 != nil {
			Usage()
			return
		}
		factory325 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt326 := factory325.GetProtocol(mbTrans323)
		argvalue0 := admin.NewGetDomainAsyncWorkflowConfiguratonRequest()
		err327 := argvalue0.Read(jsProt326)
		if err327 != nil {
			Usage()
			return
		}
		value0 := admin.GetDomainAsyncWorkflowConfiguratonRequest(argvalue0)
		fmt.Print(client.GetDomainAsyncWorkflowConfiguraton(value0))
		fmt.Print("\n")
		break
	case "UpdateDomainAsyncWorkflowConfiguraton":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateDomainAsyncWorkflowConfiguraton requires 1 args")
			flag.Usage()
		}
		arg328 := flag.Arg(1)
		mbTrans329 := thrift.NewTMemoryBufferLen(len(arg328))
		defer mbTrans329.Close()
		_, err330 := mbTrans329.WriteString(arg328)
		if err330 != nil {
			Usage()
			return
		}
		factory331 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt332 := factory331.GetProtocol(mbTrans329)
		argvalue0 := admin.NewUpdateDomainAsyncWorkflowConfiguratonRequest()
		err333 := argvalue0.Read(jsProt332)
		if err333 != nil {
			Usage()
			return
		}
		value0 := admin.UpdateDomainAsyncWorkflowConfiguratonRequest(argvalue0)
		fmt.Print(client.UpdateDomainAsyncWorkflowConfiguraton(value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
