// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package admin

import (
	"bytes"
	"config"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"replicator"
	"shared"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__
var _ = replicator.GoUnusedProtection__
var _ = config.GoUnusedProtection__

func init() {
}
