// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package shadower

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"shared"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__

const LocalDomainName = "cadence-shadower"
const TaskList = "cadence-shadower-tl"
const WorkflowName = "cadence-shadow-workflow"
const ScanWorkflowActivityName = "scanWorkflowActivity"
const ReplayWorkflowActivityName = "replayWorkflowActivity"
const WorkflowIDSuffix = "-shadow-workflow"
const ErrReasonDomainNotExists = "domain not exists"
const ErrReasonInvalidQuery = "invalid visibility query"
const ErrReasonWorkflowTypeNotRegistered = "workflow type not registered"
const ErrNonRetryableType = "com.uber.cadence.internal.shadowing.NonRetryableException"

func init() {
}
