// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package shadower

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"shared"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__
var GoUnusedProtection__ int

type Mode int64

const (
	Mode_Normal     Mode = 0
	Mode_Continuous Mode = 1
)

func (p Mode) String() string {
	switch p {
	case Mode_Normal:
		return "Normal"
	case Mode_Continuous:
		return "Continuous"
	}
	return "<UNSET>"
}

func ModeFromString(s string) (Mode, error) {
	switch s {
	case "Normal":
		return Mode_Normal, nil
	case "Continuous":
		return Mode_Continuous, nil
	}
	return Mode(0), fmt.Errorf("not a valid Mode string")
}

func ModePtr(v Mode) *Mode { return &v }

func (p Mode) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *Mode) UnmarshalText(text []byte) error {
	q, err := ModeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

// Attributes:
//   - ExpirationIntervalInSeconds
//   - ShadowCount
type ExitCondition struct {
	// unused fields # 1 to 9
	ExpirationIntervalInSeconds *int32 `thrift:"expirationIntervalInSeconds,10" json:"expirationIntervalInSeconds,omitempty"`
	// unused fields # 11 to 19
	ShadowCount *int32 `thrift:"shadowCount,20" json:"shadowCount,omitempty"`
}

func NewExitCondition() *ExitCondition {
	return &ExitCondition{}
}

var ExitCondition_ExpirationIntervalInSeconds_DEFAULT int32

func (p *ExitCondition) GetExpirationIntervalInSeconds() int32 {
	if !p.IsSetExpirationIntervalInSeconds() {
		return ExitCondition_ExpirationIntervalInSeconds_DEFAULT
	}
	return *p.ExpirationIntervalInSeconds
}

var ExitCondition_ShadowCount_DEFAULT int32

func (p *ExitCondition) GetShadowCount() int32 {
	if !p.IsSetShadowCount() {
		return ExitCondition_ShadowCount_DEFAULT
	}
	return *p.ShadowCount
}
func (p *ExitCondition) IsSetExpirationIntervalInSeconds() bool {
	return p.ExpirationIntervalInSeconds != nil
}

func (p *ExitCondition) IsSetShadowCount() bool {
	return p.ShadowCount != nil
}

func (p *ExitCondition) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ExitCondition) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.ExpirationIntervalInSeconds = &v
	}
	return nil
}

func (p *ExitCondition) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.ShadowCount = &v
	}
	return nil
}

func (p *ExitCondition) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ExitCondition"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ExitCondition) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetExpirationIntervalInSeconds() {
		if err := oprot.WriteFieldBegin("expirationIntervalInSeconds", thrift.I32, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:expirationIntervalInSeconds: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.ExpirationIntervalInSeconds)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.expirationIntervalInSeconds (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:expirationIntervalInSeconds: ", p), err)
		}
	}
	return err
}

func (p *ExitCondition) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetShadowCount() {
		if err := oprot.WriteFieldBegin("shadowCount", thrift.I32, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:shadowCount: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.ShadowCount)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.shadowCount (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:shadowCount: ", p), err)
		}
	}
	return err
}

func (p *ExitCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExitCondition(%+v)", *p)
}

// Attributes:
//   - Domain
//   - TaskList
//   - WorkflowQuery
//   - NextPageToken
//   - SamplingRate
//   - ShadowMode
//   - ExitCondition
//   - Concurrency
//   - LastRunResult_
type WorkflowParams struct {
	// unused fields # 1 to 9
	Domain *string `thrift:"domain,10" json:"domain,omitempty"`
	// unused fields # 11 to 19
	TaskList *string `thrift:"taskList,20" json:"taskList,omitempty"`
	// unused fields # 21 to 29
	WorkflowQuery *string `thrift:"workflowQuery,30" json:"workflowQuery,omitempty"`
	// unused fields # 31 to 39
	NextPageToken []byte `thrift:"nextPageToken,40" json:"nextPageToken,omitempty"`
	// unused fields # 41 to 49
	SamplingRate *float64 `thrift:"samplingRate,50" json:"samplingRate,omitempty"`
	// unused fields # 51 to 59
	ShadowMode *Mode `thrift:"shadowMode,60" json:"shadowMode,omitempty"`
	// unused fields # 61 to 69
	ExitCondition *ExitCondition `thrift:"exitCondition,70" json:"exitCondition,omitempty"`
	// unused fields # 71 to 79
	Concurrency *int32 `thrift:"concurrency,80" json:"concurrency,omitempty"`
	// unused fields # 81 to 89
	LastRunResult_ *WorkflowResult_ `thrift:"lastRunResult,90" json:"lastRunResult,omitempty"`
}

func NewWorkflowParams() *WorkflowParams {
	return &WorkflowParams{}
}

var WorkflowParams_Domain_DEFAULT string

func (p *WorkflowParams) GetDomain() string {
	if !p.IsSetDomain() {
		return WorkflowParams_Domain_DEFAULT
	}
	return *p.Domain
}

var WorkflowParams_TaskList_DEFAULT string

func (p *WorkflowParams) GetTaskList() string {
	if !p.IsSetTaskList() {
		return WorkflowParams_TaskList_DEFAULT
	}
	return *p.TaskList
}

var WorkflowParams_WorkflowQuery_DEFAULT string

func (p *WorkflowParams) GetWorkflowQuery() string {
	if !p.IsSetWorkflowQuery() {
		return WorkflowParams_WorkflowQuery_DEFAULT
	}
	return *p.WorkflowQuery
}

var WorkflowParams_NextPageToken_DEFAULT []byte

func (p *WorkflowParams) GetNextPageToken() []byte {
	return p.NextPageToken
}

var WorkflowParams_SamplingRate_DEFAULT float64

func (p *WorkflowParams) GetSamplingRate() float64 {
	if !p.IsSetSamplingRate() {
		return WorkflowParams_SamplingRate_DEFAULT
	}
	return *p.SamplingRate
}

var WorkflowParams_ShadowMode_DEFAULT Mode

func (p *WorkflowParams) GetShadowMode() Mode {
	if !p.IsSetShadowMode() {
		return WorkflowParams_ShadowMode_DEFAULT
	}
	return *p.ShadowMode
}

var WorkflowParams_ExitCondition_DEFAULT *ExitCondition

func (p *WorkflowParams) GetExitCondition() *ExitCondition {
	if !p.IsSetExitCondition() {
		return WorkflowParams_ExitCondition_DEFAULT
	}
	return p.ExitCondition
}

var WorkflowParams_Concurrency_DEFAULT int32

func (p *WorkflowParams) GetConcurrency() int32 {
	if !p.IsSetConcurrency() {
		return WorkflowParams_Concurrency_DEFAULT
	}
	return *p.Concurrency
}

var WorkflowParams_LastRunResult__DEFAULT WorkflowResult_

func (p *WorkflowParams) GetLastRunResult_() WorkflowResult_ {
	if !p.IsSetLastRunResult_() {
		return WorkflowParams_LastRunResult__DEFAULT
	}
	return *p.LastRunResult_
}
func (p *WorkflowParams) IsSetDomain() bool {
	return p.Domain != nil
}

func (p *WorkflowParams) IsSetTaskList() bool {
	return p.TaskList != nil
}

func (p *WorkflowParams) IsSetWorkflowQuery() bool {
	return p.WorkflowQuery != nil
}

func (p *WorkflowParams) IsSetNextPageToken() bool {
	return p.NextPageToken != nil
}

func (p *WorkflowParams) IsSetSamplingRate() bool {
	return p.SamplingRate != nil
}

func (p *WorkflowParams) IsSetShadowMode() bool {
	return p.ShadowMode != nil
}

func (p *WorkflowParams) IsSetExitCondition() bool {
	return p.ExitCondition != nil
}

func (p *WorkflowParams) IsSetConcurrency() bool {
	return p.Concurrency != nil
}

func (p *WorkflowParams) IsSetLastRunResult_() bool {
	return p.LastRunResult_ != nil
}

func (p *WorkflowParams) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		case 30:
			if err := p.readField30(iprot); err != nil {
				return err
			}
		case 40:
			if err := p.readField40(iprot); err != nil {
				return err
			}
		case 50:
			if err := p.readField50(iprot); err != nil {
				return err
			}
		case 60:
			if err := p.readField60(iprot); err != nil {
				return err
			}
		case 70:
			if err := p.readField70(iprot); err != nil {
				return err
			}
		case 80:
			if err := p.readField80(iprot); err != nil {
				return err
			}
		case 90:
			if err := p.readField90(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *WorkflowParams) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.Domain = &v
	}
	return nil
}

func (p *WorkflowParams) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.TaskList = &v
	}
	return nil
}

func (p *WorkflowParams) readField30(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 30: ", err)
	} else {
		p.WorkflowQuery = &v
	}
	return nil
}

func (p *WorkflowParams) readField40(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return thrift.PrependError("error reading field 40: ", err)
	} else {
		p.NextPageToken = v
	}
	return nil
}

func (p *WorkflowParams) readField50(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(); err != nil {
		return thrift.PrependError("error reading field 50: ", err)
	} else {
		p.SamplingRate = &v
	}
	return nil
}

func (p *WorkflowParams) readField60(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 60: ", err)
	} else {
		temp := Mode(v)
		p.ShadowMode = &temp
	}
	return nil
}

func (p *WorkflowParams) readField70(iprot thrift.TProtocol) error {
	p.ExitCondition = &ExitCondition{}
	if err := p.ExitCondition.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ExitCondition), err)
	}
	return nil
}

func (p *WorkflowParams) readField80(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 80: ", err)
	} else {
		p.Concurrency = &v
	}
	return nil
}

func (p *WorkflowParams) readField90(iprot thrift.TProtocol) error {
	p.LastRunResult_ = &WorkflowResult_{}
	if err := p.LastRunResult_.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.LastRunResult_), err)
	}
	return nil
}

func (p *WorkflowParams) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("WorkflowParams"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := p.writeField30(oprot); err != nil {
		return err
	}
	if err := p.writeField40(oprot); err != nil {
		return err
	}
	if err := p.writeField50(oprot); err != nil {
		return err
	}
	if err := p.writeField60(oprot); err != nil {
		return err
	}
	if err := p.writeField70(oprot); err != nil {
		return err
	}
	if err := p.writeField80(oprot); err != nil {
		return err
	}
	if err := p.writeField90(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *WorkflowParams) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetDomain() {
		if err := oprot.WriteFieldBegin("domain", thrift.STRING, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:domain: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Domain)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.domain (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:domain: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetTaskList() {
		if err := oprot.WriteFieldBegin("taskList", thrift.STRING, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:taskList: ", p), err)
		}
		if err := oprot.WriteString(string(*p.TaskList)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.taskList (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:taskList: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) writeField30(oprot thrift.TProtocol) (err error) {
	if p.IsSetWorkflowQuery() {
		if err := oprot.WriteFieldBegin("workflowQuery", thrift.STRING, 30); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 30:workflowQuery: ", p), err)
		}
		if err := oprot.WriteString(string(*p.WorkflowQuery)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.workflowQuery (30) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 30:workflowQuery: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) writeField40(oprot thrift.TProtocol) (err error) {
	if p.IsSetNextPageToken() {
		if err := oprot.WriteFieldBegin("nextPageToken", thrift.STRING, 40); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 40:nextPageToken: ", p), err)
		}
		if err := oprot.WriteBinary(p.NextPageToken); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.nextPageToken (40) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 40:nextPageToken: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) writeField50(oprot thrift.TProtocol) (err error) {
	if p.IsSetSamplingRate() {
		if err := oprot.WriteFieldBegin("samplingRate", thrift.DOUBLE, 50); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 50:samplingRate: ", p), err)
		}
		if err := oprot.WriteDouble(float64(*p.SamplingRate)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.samplingRate (50) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 50:samplingRate: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) writeField60(oprot thrift.TProtocol) (err error) {
	if p.IsSetShadowMode() {
		if err := oprot.WriteFieldBegin("shadowMode", thrift.I32, 60); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 60:shadowMode: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.ShadowMode)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.shadowMode (60) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 60:shadowMode: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) writeField70(oprot thrift.TProtocol) (err error) {
	if p.IsSetExitCondition() {
		if err := oprot.WriteFieldBegin("exitCondition", thrift.STRUCT, 70); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 70:exitCondition: ", p), err)
		}
		if err := p.ExitCondition.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ExitCondition), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 70:exitCondition: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) writeField80(oprot thrift.TProtocol) (err error) {
	if p.IsSetConcurrency() {
		if err := oprot.WriteFieldBegin("concurrency", thrift.I32, 80); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 80:concurrency: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.Concurrency)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.concurrency (80) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 80:concurrency: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) writeField90(oprot thrift.TProtocol) (err error) {
	if p.IsSetLastRunResult_() {
		if err := oprot.WriteFieldBegin("lastRunResult", thrift.STRUCT, 90); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 90:lastRunResult: ", p), err)
		}
		if err := p.LastRunResult_.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.LastRunResult_), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 90:lastRunResult: ", p), err)
		}
	}
	return err
}

func (p *WorkflowParams) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WorkflowParams(%+v)", *p)
}

// Attributes:
//   - Succeeded
//   - Skipped
//   - Failed
type WorkflowResult_ struct {
	// unused fields # 1 to 9
	Succeeded *int32 `thrift:"succeeded,10" json:"succeeded,omitempty"`
	// unused fields # 11 to 19
	Skipped *int32 `thrift:"skipped,20" json:"skipped,omitempty"`
	// unused fields # 21 to 29
	Failed *int32 `thrift:"failed,30" json:"failed,omitempty"`
}

func NewWorkflowResult_() *WorkflowResult_ {
	return &WorkflowResult_{}
}

var WorkflowResult__Succeeded_DEFAULT int32

func (p *WorkflowResult_) GetSucceeded() int32 {
	if !p.IsSetSucceeded() {
		return WorkflowResult__Succeeded_DEFAULT
	}
	return *p.Succeeded
}

var WorkflowResult__Skipped_DEFAULT int32

func (p *WorkflowResult_) GetSkipped() int32 {
	if !p.IsSetSkipped() {
		return WorkflowResult__Skipped_DEFAULT
	}
	return *p.Skipped
}

var WorkflowResult__Failed_DEFAULT int32

func (p *WorkflowResult_) GetFailed() int32 {
	if !p.IsSetFailed() {
		return WorkflowResult__Failed_DEFAULT
	}
	return *p.Failed
}
func (p *WorkflowResult_) IsSetSucceeded() bool {
	return p.Succeeded != nil
}

func (p *WorkflowResult_) IsSetSkipped() bool {
	return p.Skipped != nil
}

func (p *WorkflowResult_) IsSetFailed() bool {
	return p.Failed != nil
}

func (p *WorkflowResult_) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		case 30:
			if err := p.readField30(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *WorkflowResult_) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.Succeeded = &v
	}
	return nil
}

func (p *WorkflowResult_) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.Skipped = &v
	}
	return nil
}

func (p *WorkflowResult_) readField30(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 30: ", err)
	} else {
		p.Failed = &v
	}
	return nil
}

func (p *WorkflowResult_) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("WorkflowResult"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := p.writeField30(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *WorkflowResult_) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetSucceeded() {
		if err := oprot.WriteFieldBegin("succeeded", thrift.I32, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:succeeded: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.Succeeded)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.succeeded (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:succeeded: ", p), err)
		}
	}
	return err
}

func (p *WorkflowResult_) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetSkipped() {
		if err := oprot.WriteFieldBegin("skipped", thrift.I32, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:skipped: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.Skipped)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.skipped (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:skipped: ", p), err)
		}
	}
	return err
}

func (p *WorkflowResult_) writeField30(oprot thrift.TProtocol) (err error) {
	if p.IsSetFailed() {
		if err := oprot.WriteFieldBegin("failed", thrift.I32, 30); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 30:failed: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.Failed)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.failed (30) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 30:failed: ", p), err)
		}
	}
	return err
}

func (p *WorkflowResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WorkflowResult_(%+v)", *p)
}

// Attributes:
//   - Domain
//   - WorkflowQuery
//   - NextPageToken
//   - PageSize
//   - SamplingRate
type ScanWorkflowActivityParams struct {
	// unused fields # 1 to 9
	Domain *string `thrift:"domain,10" json:"domain,omitempty"`
	// unused fields # 11 to 19
	WorkflowQuery *string `thrift:"workflowQuery,20" json:"workflowQuery,omitempty"`
	// unused fields # 21 to 29
	NextPageToken []byte `thrift:"nextPageToken,30" json:"nextPageToken,omitempty"`
	// unused fields # 31 to 39
	PageSize *int32 `thrift:"pageSize,40" json:"pageSize,omitempty"`
	// unused fields # 41 to 49
	SamplingRate *float64 `thrift:"samplingRate,50" json:"samplingRate,omitempty"`
}

func NewScanWorkflowActivityParams() *ScanWorkflowActivityParams {
	return &ScanWorkflowActivityParams{}
}

var ScanWorkflowActivityParams_Domain_DEFAULT string

func (p *ScanWorkflowActivityParams) GetDomain() string {
	if !p.IsSetDomain() {
		return ScanWorkflowActivityParams_Domain_DEFAULT
	}
	return *p.Domain
}

var ScanWorkflowActivityParams_WorkflowQuery_DEFAULT string

func (p *ScanWorkflowActivityParams) GetWorkflowQuery() string {
	if !p.IsSetWorkflowQuery() {
		return ScanWorkflowActivityParams_WorkflowQuery_DEFAULT
	}
	return *p.WorkflowQuery
}

var ScanWorkflowActivityParams_NextPageToken_DEFAULT []byte

func (p *ScanWorkflowActivityParams) GetNextPageToken() []byte {
	return p.NextPageToken
}

var ScanWorkflowActivityParams_PageSize_DEFAULT int32

func (p *ScanWorkflowActivityParams) GetPageSize() int32 {
	if !p.IsSetPageSize() {
		return ScanWorkflowActivityParams_PageSize_DEFAULT
	}
	return *p.PageSize
}

var ScanWorkflowActivityParams_SamplingRate_DEFAULT float64

func (p *ScanWorkflowActivityParams) GetSamplingRate() float64 {
	if !p.IsSetSamplingRate() {
		return ScanWorkflowActivityParams_SamplingRate_DEFAULT
	}
	return *p.SamplingRate
}
func (p *ScanWorkflowActivityParams) IsSetDomain() bool {
	return p.Domain != nil
}

func (p *ScanWorkflowActivityParams) IsSetWorkflowQuery() bool {
	return p.WorkflowQuery != nil
}

func (p *ScanWorkflowActivityParams) IsSetNextPageToken() bool {
	return p.NextPageToken != nil
}

func (p *ScanWorkflowActivityParams) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *ScanWorkflowActivityParams) IsSetSamplingRate() bool {
	return p.SamplingRate != nil
}

func (p *ScanWorkflowActivityParams) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		case 30:
			if err := p.readField30(iprot); err != nil {
				return err
			}
		case 40:
			if err := p.readField40(iprot); err != nil {
				return err
			}
		case 50:
			if err := p.readField50(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ScanWorkflowActivityParams) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.Domain = &v
	}
	return nil
}

func (p *ScanWorkflowActivityParams) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.WorkflowQuery = &v
	}
	return nil
}

func (p *ScanWorkflowActivityParams) readField30(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return thrift.PrependError("error reading field 30: ", err)
	} else {
		p.NextPageToken = v
	}
	return nil
}

func (p *ScanWorkflowActivityParams) readField40(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 40: ", err)
	} else {
		p.PageSize = &v
	}
	return nil
}

func (p *ScanWorkflowActivityParams) readField50(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(); err != nil {
		return thrift.PrependError("error reading field 50: ", err)
	} else {
		p.SamplingRate = &v
	}
	return nil
}

func (p *ScanWorkflowActivityParams) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ScanWorkflowActivityParams"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := p.writeField30(oprot); err != nil {
		return err
	}
	if err := p.writeField40(oprot); err != nil {
		return err
	}
	if err := p.writeField50(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ScanWorkflowActivityParams) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetDomain() {
		if err := oprot.WriteFieldBegin("domain", thrift.STRING, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:domain: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Domain)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.domain (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:domain: ", p), err)
		}
	}
	return err
}

func (p *ScanWorkflowActivityParams) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetWorkflowQuery() {
		if err := oprot.WriteFieldBegin("workflowQuery", thrift.STRING, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:workflowQuery: ", p), err)
		}
		if err := oprot.WriteString(string(*p.WorkflowQuery)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.workflowQuery (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:workflowQuery: ", p), err)
		}
	}
	return err
}

func (p *ScanWorkflowActivityParams) writeField30(oprot thrift.TProtocol) (err error) {
	if p.IsSetNextPageToken() {
		if err := oprot.WriteFieldBegin("nextPageToken", thrift.STRING, 30); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 30:nextPageToken: ", p), err)
		}
		if err := oprot.WriteBinary(p.NextPageToken); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.nextPageToken (30) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 30:nextPageToken: ", p), err)
		}
	}
	return err
}

func (p *ScanWorkflowActivityParams) writeField40(oprot thrift.TProtocol) (err error) {
	if p.IsSetPageSize() {
		if err := oprot.WriteFieldBegin("pageSize", thrift.I32, 40); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 40:pageSize: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.PageSize)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.pageSize (40) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 40:pageSize: ", p), err)
		}
	}
	return err
}

func (p *ScanWorkflowActivityParams) writeField50(oprot thrift.TProtocol) (err error) {
	if p.IsSetSamplingRate() {
		if err := oprot.WriteFieldBegin("samplingRate", thrift.DOUBLE, 50); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 50:samplingRate: ", p), err)
		}
		if err := oprot.WriteDouble(float64(*p.SamplingRate)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.samplingRate (50) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 50:samplingRate: ", p), err)
		}
	}
	return err
}

func (p *ScanWorkflowActivityParams) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScanWorkflowActivityParams(%+v)", *p)
}

// Attributes:
//   - Executions
//   - NextPageToken
type ScanWorkflowActivityResult_ struct {
	// unused fields # 1 to 9
	Executions []*shared.WorkflowExecution `thrift:"executions,10" json:"executions,omitempty"`
	// unused fields # 11 to 19
	NextPageToken []byte `thrift:"nextPageToken,20" json:"nextPageToken,omitempty"`
}

func NewScanWorkflowActivityResult_() *ScanWorkflowActivityResult_ {
	return &ScanWorkflowActivityResult_{}
}

var ScanWorkflowActivityResult__Executions_DEFAULT []*shared.WorkflowExecution

func (p *ScanWorkflowActivityResult_) GetExecutions() []*shared.WorkflowExecution {
	return p.Executions
}

var ScanWorkflowActivityResult__NextPageToken_DEFAULT []byte

func (p *ScanWorkflowActivityResult_) GetNextPageToken() []byte {
	return p.NextPageToken
}
func (p *ScanWorkflowActivityResult_) IsSetExecutions() bool {
	return p.Executions != nil
}

func (p *ScanWorkflowActivityResult_) IsSetNextPageToken() bool {
	return p.NextPageToken != nil
}

func (p *ScanWorkflowActivityResult_) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ScanWorkflowActivityResult_) readField10(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*shared.WorkflowExecution, 0, size)
	p.Executions = tSlice
	for i := 0; i < size; i++ {
		_elem0 := &shared.WorkflowExecution{}
		if err := _elem0.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem0), err)
		}
		p.Executions = append(p.Executions, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *ScanWorkflowActivityResult_) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.NextPageToken = v
	}
	return nil
}

func (p *ScanWorkflowActivityResult_) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ScanWorkflowActivityResult"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ScanWorkflowActivityResult_) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetExecutions() {
		if err := oprot.WriteFieldBegin("executions", thrift.LIST, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:executions: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Executions)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Executions {
			if err := v.Write(oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:executions: ", p), err)
		}
	}
	return err
}

func (p *ScanWorkflowActivityResult_) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetNextPageToken() {
		if err := oprot.WriteFieldBegin("nextPageToken", thrift.STRING, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:nextPageToken: ", p), err)
		}
		if err := oprot.WriteBinary(p.NextPageToken); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.nextPageToken (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:nextPageToken: ", p), err)
		}
	}
	return err
}

func (p *ScanWorkflowActivityResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ScanWorkflowActivityResult_(%+v)", *p)
}

// Attributes:
//   - Domain
//   - Executions
type ReplayWorkflowActivityParams struct {
	// unused fields # 1 to 9
	Domain *string `thrift:"domain,10" json:"domain,omitempty"`
	// unused fields # 11 to 19
	Executions []*shared.WorkflowExecution `thrift:"executions,20" json:"executions,omitempty"`
}

func NewReplayWorkflowActivityParams() *ReplayWorkflowActivityParams {
	return &ReplayWorkflowActivityParams{}
}

var ReplayWorkflowActivityParams_Domain_DEFAULT string

func (p *ReplayWorkflowActivityParams) GetDomain() string {
	if !p.IsSetDomain() {
		return ReplayWorkflowActivityParams_Domain_DEFAULT
	}
	return *p.Domain
}

var ReplayWorkflowActivityParams_Executions_DEFAULT []*shared.WorkflowExecution

func (p *ReplayWorkflowActivityParams) GetExecutions() []*shared.WorkflowExecution {
	return p.Executions
}
func (p *ReplayWorkflowActivityParams) IsSetDomain() bool {
	return p.Domain != nil
}

func (p *ReplayWorkflowActivityParams) IsSetExecutions() bool {
	return p.Executions != nil
}

func (p *ReplayWorkflowActivityParams) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ReplayWorkflowActivityParams) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.Domain = &v
	}
	return nil
}

func (p *ReplayWorkflowActivityParams) readField20(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*shared.WorkflowExecution, 0, size)
	p.Executions = tSlice
	for i := 0; i < size; i++ {
		_elem1 := &shared.WorkflowExecution{}
		if err := _elem1.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem1), err)
		}
		p.Executions = append(p.Executions, _elem1)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *ReplayWorkflowActivityParams) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ReplayWorkflowActivityParams"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ReplayWorkflowActivityParams) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetDomain() {
		if err := oprot.WriteFieldBegin("domain", thrift.STRING, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:domain: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Domain)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.domain (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:domain: ", p), err)
		}
	}
	return err
}

func (p *ReplayWorkflowActivityParams) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetExecutions() {
		if err := oprot.WriteFieldBegin("executions", thrift.LIST, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:executions: ", p), err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Executions)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Executions {
			if err := v.Write(oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:executions: ", p), err)
		}
	}
	return err
}

func (p *ReplayWorkflowActivityParams) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReplayWorkflowActivityParams(%+v)", *p)
}

// Attributes:
//   - Succeeded
//   - Skipped
//   - Failed
type ReplayWorkflowActivityResult_ struct {
	// unused fields # 1 to 9
	Succeeded *int32 `thrift:"succeeded,10" json:"succeeded,omitempty"`
	// unused fields # 11 to 19
	Skipped *int32 `thrift:"skipped,20" json:"skipped,omitempty"`
	// unused fields # 21 to 29
	Failed *int32 `thrift:"failed,30" json:"failed,omitempty"`
}

func NewReplayWorkflowActivityResult_() *ReplayWorkflowActivityResult_ {
	return &ReplayWorkflowActivityResult_{}
}

var ReplayWorkflowActivityResult__Succeeded_DEFAULT int32

func (p *ReplayWorkflowActivityResult_) GetSucceeded() int32 {
	if !p.IsSetSucceeded() {
		return ReplayWorkflowActivityResult__Succeeded_DEFAULT
	}
	return *p.Succeeded
}

var ReplayWorkflowActivityResult__Skipped_DEFAULT int32

func (p *ReplayWorkflowActivityResult_) GetSkipped() int32 {
	if !p.IsSetSkipped() {
		return ReplayWorkflowActivityResult__Skipped_DEFAULT
	}
	return *p.Skipped
}

var ReplayWorkflowActivityResult__Failed_DEFAULT int32

func (p *ReplayWorkflowActivityResult_) GetFailed() int32 {
	if !p.IsSetFailed() {
		return ReplayWorkflowActivityResult__Failed_DEFAULT
	}
	return *p.Failed
}
func (p *ReplayWorkflowActivityResult_) IsSetSucceeded() bool {
	return p.Succeeded != nil
}

func (p *ReplayWorkflowActivityResult_) IsSetSkipped() bool {
	return p.Skipped != nil
}

func (p *ReplayWorkflowActivityResult_) IsSetFailed() bool {
	return p.Failed != nil
}

func (p *ReplayWorkflowActivityResult_) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 10:
			if err := p.readField10(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.readField20(iprot); err != nil {
				return err
			}
		case 30:
			if err := p.readField30(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ReplayWorkflowActivityResult_) readField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.Succeeded = &v
	}
	return nil
}

func (p *ReplayWorkflowActivityResult_) readField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 20: ", err)
	} else {
		p.Skipped = &v
	}
	return nil
}

func (p *ReplayWorkflowActivityResult_) readField30(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 30: ", err)
	} else {
		p.Failed = &v
	}
	return nil
}

func (p *ReplayWorkflowActivityResult_) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ReplayWorkflowActivityResult"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := p.writeField30(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ReplayWorkflowActivityResult_) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetSucceeded() {
		if err := oprot.WriteFieldBegin("succeeded", thrift.I32, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:succeeded: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.Succeeded)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.succeeded (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:succeeded: ", p), err)
		}
	}
	return err
}

func (p *ReplayWorkflowActivityResult_) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetSkipped() {
		if err := oprot.WriteFieldBegin("skipped", thrift.I32, 20); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 20:skipped: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.Skipped)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.skipped (20) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 20:skipped: ", p), err)
		}
	}
	return err
}

func (p *ReplayWorkflowActivityResult_) writeField30(oprot thrift.TProtocol) (err error) {
	if p.IsSetFailed() {
		if err := oprot.WriteFieldBegin("failed", thrift.I32, 30); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 30:failed: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.Failed)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.failed (30) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 30:failed: ", p), err)
		}
	}
	return err
}

func (p *ReplayWorkflowActivityResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReplayWorkflowActivityResult_(%+v)", *p)
}
